### ISSUE TITLE
Wrong occlusions

### ISSUE THREAD

**Issue by NikolasE** [ros-visualization/rviz#1006]
Hey!

I have some problems with the occlusion detection (looks like a wrong z-buffer):
![box_a](https://cloud.githubusercontent.com/assets/489623/15098423/de9658de-153d-11e6-993a-27ac714dd140.png)
![box_b](https://cloud.githubusercontent.com/assets/489623/15098424/dffd1aaa-153d-11e6-8eb3-bceedb5b91df.png)

Depending on the camera pose, the bottom of the box is rendered on top of the wall. This also happens for other marker types. 

I'm using an Nvidia GPU, about RVIZ:

This is RViz version 1.11.14 (indigo).
Compiled against Qt version 4.8.6.
Compiled against OGRE version 1.8.1 (Byatis).

Has anyone else seen this behaviour? What other information should I provide on my setup?

Discussion on answers.ros: http://answers.ros.org/question/233609/wrong-occlusions-in-rviz/

**Comment by wjwwood** [comment]
I don't know what would cause that, but if you have a bag file that can be used to reproduce it that would help.
