### ISSUE TITLE
Adding new display takes time by 'Add' button (popping up the select window takes time)

### ISSUE THREAD

**Issue by wkentaro** [ros-visualization/rviz#1014]
I added 'Duplicate' button in https://github.com/ros-visualization/rviz/pull/977
It's really faster than adding displays with 'Add' button, so I wonder why.

--

**Update**
I found collecting display type list takes time. With 52 display types, [this line](https://github.com/ros-visualization/rviz/blob/kinetic-devel/src/rviz/add_display_dialog.cpp#L196) takes around 3s on my PC.

--

**Update**
I found [this line](https://github.com/ros-visualization/rviz/blob/kinetic-devel/src/rviz/add_display_dialog.cpp#L422) takes time.
By commenting out it, [that](https://github.com/ros-visualization/rviz/blob/kinetic-devel/src/rviz/add_display_dialog.cpp#L196) taking time become 0.06s.
Maybe caching does not work [here](https://github.com/ros-visualization/rviz/blob/kinetic-devel/src/rviz/load_resource.cpp#L91). It always loads pixmap when I check it by print debugging.

**Comment by wjwwood** [comment]
Is this related to https://github.com/ros-visualization/rviz/pull/966?

**Comment by wkentaro** [comment]
The problem of slow popping up of the display is fixed via 
- https://github.com/jsk-ros-pkg/jsk_visualization/pull/605
- https://github.com/jsk-ros-pkg/jsk_visualization/issues/603
by resizing the large icon to smaller one.

I'm not sure if the caching does work, but this problem is fixed for me.
