### ISSUE TITLE
focal_shape_ size should depend on distance_property_

### ISSUE THREAD

**Issue by VictorLamoine** [ros-visualization/rviz#1020]
When using RViz and zooming on very small objects in RViz the `focal_shape_` (the yellow squeezed sphere on the screenshot) becomes very big and clutters the view.
The inverse happens when zooming out, we can't see the focal shape anymore.

![focal_shape_](https://cloud.githubusercontent.com/assets/5566160/15848905/db72145e-2c8f-11e6-8152-67f5a33da302.png)

We should resize the sphere as the user zooms in/out so that it always remains visible but never too big.

https://github.com/ros-visualization/rviz/blob/indigo-devel/src/rviz/default_plugin/view_controllers/orbit_view_controller.cpp#L80

**Comment by trainman419** [comment]
When zooming or panning an empty world, the focal shape is often my only visual cue about what the current zoom level is. Having the focal shape scale dynamically counteracts this.

A simpler approach that maintains the functionality that I use on a regular basis would be to make the size of the focal shape settable by the user.
