### ISSUE TITLE
rviz Kinetic armhf crashes when loading stl mesh

### ISSUE THREAD

**Issue by bsaund** [ros-visualization/rviz#1046]
I am running ROS Kinetic on a Raspberry Pi 3 Ubuntu 16.04. Rviz successfully displays the built in marker types, but crashes when displaying a mesh_resource. The same code successfully displays the mesh in rviz in Indigo on a different computer.

This branch shows the issue:
https://github.com/bsaund/UpdatedBalancingRobot/tree/RvizCrashIssue

**Comment by wjwwood** [comment]
I think this is a duplicate of https://github.com/ros-visualization/rviz/issues/850. I'll close it and if you disagree then comment here and I'll reopen it. Thanks.
