### ISSUE TITLE
focal point marker can appear blueish

### ISSUE THREAD

**Issue by wjwwood** [ros-visualization/rviz#1056]
Normally it would be yellow. I can reproduce this in a Xenial VM on my macbook by running `roslaunch navigation_stage move_base_amcl_2.5cm.launch`.

<img width="1280" alt="screen shot 2016-10-17 at 11 14 49 am" src="https://cloud.githubusercontent.com/assets/100427/19449578/f195f9d4-945a-11e6-8965-bff25053d288.png">

**Comment by VictorLamoine** [comment]
This is expected and not a bug:
https://github.com/ros-visualization/rviz/blob/kinetic-devel/src/rviz/default_plugin/view_controllers/third_person_follower_view_controller.cpp#L60

Switch back to `Orbit (rviz)` view controller to get the yellow focal shape.

**Comment by wjwwood** [comment]
Ah right, I even remember that now... Thanks.
