### ISSUE TITLE
OccupancyGrid display ignores timestamps

### ISSUE THREAD

**Issue by ayrton04** [ros-visualization/rviz#1065]
The OccupancyGrid plugin (MapDisplay) is [transforming](https://github.com/ros-visualization/rviz/blob/kinetic-devel/src/rviz/default_plugin/map_display.cpp#L707) the map using a time stamp of `ros::Time()` instead of `current_map_.header.stamp`. If this was intentional, perhaps we can add an option to use the header's time stamp? I'd be happy to submit a PR.

**Comment by wjwwood** [comment]
I'm not sure if it was intentional or not. @hersh @DLu can either of you think of a reason the current time was used for the transform in the MapDisplay rather than using the timestamp in the header? Either way, having an option (which defaults to the current behavior) would not do any harm.

**Comment by NikolausDemmel** [comment]
When the `OccupancyGrid` represents a grid map, I would assume that `header.stamp` would correspond to the map-creation time, which for the typical localization scenario would lie far in the past and outside the TF buffer, so I think the current behaviour as a default makes sense for that scenario, but I understand that for different uses of OccupancyGrid this might make less sense.

**Comment by DLu** [comment]
Nothing comes to mind.

**Comment by wjwwood** [comment]
Closed with https://github.com/ros-visualization/rviz/pull/1066
