### ISSUE TITLE
How to get the goal state of robot in Rviz by programming?

### ISSUE THREAD

**Issue by LMNcnu** [ros-visualization/rviz#1072]
In the Rviz, I drag the marker on an arm of robot, then the orange color represent the goal state. How to get the goal state（just the orange arm） by programming?
![image](https://cloud.githubusercontent.com/assets/16238857/21603556/2db31878-d1d9-11e6-8e33-c04dac14abca.png)

**Comment by wjwwood** [comment]
I believe you're using the moveit rviz plugin, you'd be better off asking about that (it is not rviz specific). Also you should ask this on [answers.ros.org](http://answers.ros.org/questions/) and only use issue trackers for bugs or enhancement requests, see: http://wiki.ros.org/Support#When_something_fails
