### ISSUE TITLE
Datatype mismatch error while visualizing Marker object 

### ISSUE THREAD

**Issue by Karnix** [ros-visualization/rviz#1083]
Hi!

I'm trying to visualize Marker objects of type cube list that are being published on my Odroid SBC running ROS Kinetic Kame, on my laptop running ROS Indigo. Both are using the same ROS master.

But I get the following error,

[ERROR] [1488184609.243649838]: Client [/rviz_1488184582080327521] wants topic /visualization_marker to have datatype/md5sum [visualization_msgs/Marker/18326976df9d29249efc939e00342cde], but our version has [visualization_msgs/Marker/4048c9de2a16f4ae8e0538085ebf1b97]. Dropping connection.

Is this a case of no backward compatibility?

**Comment by wjwwood** [comment]
Yeah, a define was added in ROS Jade:

https://github.com/ros/common_msgs/commit/7e116353e9562885cb5e0e568864971fa27d65df
