### ISSUE TITLE
Slow Rendering of High-Poly Models

### ISSUE THREAD

**Issue by Jmeyer1292** [ros-visualization/rviz#1086]
I'm stuck on a performance issue related to RVIZ and I'd like to at least ask if anyone has experience with something similar.

I'm using ROS kinetic on 16.04.2.

I've put together a desktop machine and am facing a "strange" performance bug.

I run the following command to visualize a [URDF](https://github.com/ros-industrial-consortium/godel/blob/kinetic-devel/godel_robots/abb/godel_irb2400/godel_irb2400_support/urdf/irb2400_workspace.xacro) from our open-source robotic blending project:
```
roslaunch urdf_tutorial xacrodisplay.launch model:=irb2400_workspace.xacro
```

There are some (mildly) high poly models that make up the end-effector of that model. When visualizing those models, my frame rate tanks to ~2 Hz. CPU usage spikes.

On my laptop, using integrated graphics I get silky smooth results with little to no CPU utilization. On this new desktop, trying both an older known good Quadro card and a newer Geforce 980 Ti I experience these frame drops. I have tried the 375 drivers installed by CUDA and the 367 drivers in Ubuntu. I did a purge and used the default driver and got the same results.

I've run `glmark2` benchmarks and the CUDA samples and performance of the graphics cards seem reasonable and correct.

I've tried the debian version of RViz and built against source. RViz shows we're using opengl 4.5 when launching.

**Comment by wjwwood** [comment]
@Jmeyer1292 so, did you fix it or why did you close it?

**Comment by Jmeyer1292** [comment]
I did the fix the issue, but I'm not entirely sure how. Some combination of blacklisting `nouveau` (which wasn't done automatically?) and changing driver versions made it work. I'm not sure exactly what I did.

I apologize for bothering you.

**Comment by wjwwood** [comment]
No worries, just didn't know what the final state was 😄.
