### ISSUE TITLE
Release into ROS Lunar

### ISSUE THREAD

**Issue by 130s** [ros-visualization/rviz#1090]
Apparently this blocks the release of [dozens of packages](http://repositories.ros.org/status_page/blocked_releases_lunar.html?s=6&r=1).
Thanks!

**Comment by mikaelarguedas** [comment]
This is currently blocked by https://github.com/ros-planning/navigation_msgs/issues/2

**Comment by wjwwood** [comment]
What @mikaelarguedas said, also I need to triage the tickets to see what needs to go into Lunar only, if anything.

**Comment by davetcoleman** [comment]
navigation_msgs is now released

**Comment by 130s** [comment]
Thanks @wjwwood 
https://github.com/ros/rosdistro/pull/14559
