### ISSUE TITLE
rviz can not work and catkin_make error

### ISSUE THREAD

**Issue by zhehangT** [ros-visualization/rviz#1103]
Ubuntu: 16.04
ROS:kinetic

Today when I startup rviz, it can not work as #1047. 
![2017-05-13 16-07-05](https://cloud.githubusercontent.com/assets/8287252/26023828/99df78b4-37f7-11e7-9cb1-1ccbee1cab2a.png)

It seems to be the qt version incompatible as rviz compiled against **Qt version 5.5.1** while the Qt version in my ubuntu is Qt version 5.6.1. However I not sure.
![2017-05-13 16-15-31](https://cloud.githubusercontent.com/assets/8287252/26023830/a2631644-37f7-11e7-9957-e48655f30780.png)
![2017-05-13 16-16-03](https://cloud.githubusercontent.com/assets/8287252/26023831/a52f469a-37f7-11e7-913d-ba8c583b1874.png)

I try to fix the rviz by compiling it in my catkin workspace. But it fails again because of the catkin_make error. 
yaml-cpp I am using is 0.5.3.

I don't know how to continue fix the rviz.

```
[ 57%] Linking CXX executable /home/tzh/rviz_ws/devel/lib/rviz/image_view
[ 88%] Built target rviz_default_plugin
[ 89%] Linking CXX executable /home/tzh/rviz_ws/devel/lib/rviz/line_edit_with_button_test
/home/tzh/rviz_ws/devel/lib/librviz.so: undefined reference to `vtable for YAML::BadConversion'
/home/tzh/rviz_ws/devel/lib/librviz.so: undefined reference to `typeinfo for YAML::BadConversion'
/home/tzh/rviz_ws/devel/lib/librviz.so: undefined reference to `YAML::BadConversion::~BadConversion()'
collect2: error: ld returned 1 exit status
rviz/src/test/CMakeFiles/render_points_test.dir/build.make:204: recipe for target '/home/tzh/rviz_ws/devel/lib/rviz/render_points_test' failed
make[2]: *** [/home/tzh/rviz_ws/devel/lib/rviz/render_points_test] Error 1
CMakeFiles/Makefile2:3143: recipe for target 'rviz/src/test/CMakeFiles/render_points_test.dir/all' failed
make[1]: *** [rviz/src/test/CMakeFiles/render_points_test.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/home/tzh/rviz_ws/devel/lib/librviz.so: undefined reference to `vtable for YAML::BadConversion'
/home/tzh/rviz_ws/devel/lib/librviz.so: undefined reference to `typeinfo for YAML::BadConversion'
/home/tzh/rviz_ws/devel/lib/librviz.so: undefined reference to `YAML::BadConversion::~BadConversion()'
collect2: error: ld returned 1 exit status
rviz/src/test/CMakeFiles/line_edit_with_button_test.dir/build.make:178: recipe for target '/home/tzh/rviz_ws/devel/lib/rviz/line_edit_with_button_test' failed
make[2]: *** [/home/tzh/rviz_ws/devel/lib/rviz/line_edit_with_button_test] Error 1
CMakeFiles/Makefile2:3215: recipe for target 'rviz/src/test/CMakeFiles/line_edit_with_button_test.dir/all' failed
make[1]: *** [rviz/src/test/CMakeFiles/line_edit_with_button_test.dir/all] Error 2
/home/tzh/rviz_ws/devel/lib/librviz.so: undefined reference to `vtable for YAML::BadConversion'
/home/tzh/rviz_ws/devel/lib/librviz.so: undefined reference to `typeinfo for YAML::BadConversion'
/home/tzh/rviz_ws/devel/lib/librviz.so: undefined reference to `YAML::BadConversion::~BadConversion()'
collect2: error: ld returned 1 exit status
rviz/src/image_view/CMakeFiles/rviz_image_view.dir/build.make:250: recipe for target '/home/tzh/rviz_ws/devel/lib/rviz/image_view' failed
make[2]: *** [/home/tzh/rviz_ws/devel/lib/rviz/image_view] Error 1
CMakeFiles/Makefile2:2958: recipe for target 'rviz/src/image_view/CMakeFiles/rviz_image_view.dir/all' failed
make[1]: *** [rviz/src/image_view/CMakeFiles/rviz_image_view.dir/all] Error 2
/home/tzh/rviz_ws/devel/lib/librviz.so: undefined reference to `vtable for YAML::BadConversion'
/home/tzh/rviz_ws/devel/lib/librviz.so: undefined reference to `typeinfo for YAML::BadConversion'
/home/tzh/rviz_ws/devel/lib/librviz.so: undefined reference to `YAML::BadConversion::~BadConversion()'
collect2: error: ld returned 1 exit status
rviz/src/rviz/CMakeFiles/executable.dir/build.make:224: recipe for target '/home/tzh/rviz_ws/devel/lib/rviz/rviz' failed
make[2]: *** [/home/tzh/rviz_ws/devel/lib/rviz/rviz] Error 1
CMakeFiles/Makefile2:2711: recipe for target 'rviz/src/rviz/CMakeFiles/executable.dir/all' failed
make[1]: *** [rviz/src/rviz/CMakeFiles/executable.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j4 -l4" failed
```

**Comment by wjwwood** [comment]
Please do not post screenshots of text. I cannot be searched or copy-pasted.

Please make sure you have done `sudo apt update` and then `sudo apt install ros-kinetic-rviz`. My machine is using the right versions of qt. Also I can build rviz (branch `kinetic-devel`) from source too. It seems like the only possibility is that your machine has the wrong versions of dependencies. You might also check to make sure you do not have extra PPA's that are pulling in newer versions of libraries like yaml-cpp and qt.

**Comment by zhehangT** [comment]
@wjwwood Sorry for posting screenshots of text.

I am wondering what version of yaml-cpp and qt  in your machine.
Thank you.

**Comment by zhehangT** [comment]
I compile rviz in my catkin workspace but rviz can not work as well. Just like #1047.

Don not know how to fix it. Sad.

**Comment by zhehangT** [comment]
I remove the yaml-cpp I installed manual from the github, rviz can wok well.
Maybe the conflict of yaml-cpp version cause the crash

**Comment by wjwwood** [comment]
> I remove the yaml-cpp I installed manual from the github

Yup.

> I am wondering what version of yaml-cpp and qt in your machine.

I have Qt `5.5.1` and yaml-cpp `0.5.2-3`.

**Comment by bigbellmercy** [comment]
In my case, the errors like the title of this issue disappeared after `rviz` source code reinstalled from its GitHub site.
My environment: Ubuntu 18.04, caktin build (not cakin_make), ROS Melodic
