### ISSUE TITLE
Allow to use scroll buttons in QTabWidgets created by RViz

### ISSUE THREAD

**Issue by VictorLamoine** [ros-visualization/rviz#1148]
If you stack a lot of widgets inside RViz, the labels becomes hard to read like this:
![capture du 2017-09-11 11-17-43](https://user-images.githubusercontent.com/5566160/30267456-f1e74d44-96e2-11e7-9c04-c069e71662be.png)

Solutions:
- Use shorter tab names (+ a tooltip)
- Expand the tab so that labels becomes easy to read again:
![capture du 2017-09-11 11-17-54](https://user-images.githubusercontent.com/5566160/30267458-f390e9b6-96e2-11e7-90f8-ad861ce50df4.png)
- Allow to use [scroll buttons](http://doc.qt.io/qt-5/qtabwidget.html#usesScrollButtons-prop) in the QTabWidget:
  - ![fusion-tabbar](http://doc.qt.io/qt-5/images/fusion-tabbar.png) (without scroll buttons)
  - ![fusion-tabbar-truncated](http://doc.qt.io/qt-5/images/fusion-tabbar-truncated.png) (with scroll buttons)

Last solution is by far the best in my opinion.
I think one solution is to subclass the tab bar and add a right click action to choose between scroll buttons, no scroll buttons.

**Comment by VictorLamoine** [comment]
I can't find the code that manages that part. I searched for QTabWidget but it's only returning one results which is not what I'm looking for (`src/rviz/add_display_dialog.cpp`).

Which part of the RViz code manages the stacking/moving of whole RViz panels?

**Comment by wjwwood** [comment]
@VictorLamoine I believe it is just done by `QtMainWindow` (of which `VisualizationFrame` inherits). Maybe what you want is https://doc.qt.io/qt-5/qmainwindow.html#DockOption-enum?

**Comment by VictorLamoine** [comment]
Thanks @wjwwood, it helped me a lot because I did not know the "dock widget" names.

I made a test and this is exactly what I wanted:

# Default behaviour
![default_behaviour](https://user-images.githubusercontent.com/5566160/32040911-9860d0ba-ba32-11e7-9f33-edaf2a517380.png)

# Don't elide text in QTabBar
![no_elide](https://user-images.githubusercontent.com/5566160/32040918-9f6a51b0-ba32-11e7-87e2-cf3bea03b50c.png)

Now I need to find a place/signal to put this code (each time a panel is added or moved); the code itself is very straightforward:

https://github.com/ros-visualization/rviz/compare/kinetic-devel...VictorLamoine:QTabWidget_elide?expand=1

**Comment by gavanderhoorn** [comment]
Diff without whitespace changes: https://github.com/ros-visualization/rviz/compare/kinetic-devel...VictorLamoine:QTabWidget_elide?expand=1&w=1.
