### ISSUE TITLE
Enable copy of values from the Displays panel to system clipboard

### ISSUE THREAD

**Issue by ferrolho** [ros-visualization/rviz#1156]
It is not the first time that I've found myself hitting <kbd>CTRL</kbd> + <kbd>C</kbd> trying to copy some joint position from rviz...

It would be very handy to be able to copy values from the `Displays` panel into the system clipboard.

![screenshot from 2017-10-03 22 40 08](https://user-images.githubusercontent.com/4166093/31150558-f27d7e12-a88b-11e7-9bf3-a73d4182f655.png)

**Comment by felixvd** [comment]
I can copy values on Ubuntu 18.04, although it sometimes requires hitting Ctrl-C multiple times.

**Comment by rhaschke** [comment]
For me, copying works as expected as well. Closing this issue.
