### ISSUE TITLE
how to run this program?

### ISSUE THREAD

**Issue by buzzo123** [ros-visualization/rviz#1166]
hi, can someone explain to me how to run this program? thanks

**Comment by lucbettaieb** [comment]
@buzzo123 Hi, you can type `rviz` in the terminal after installing ROS.  Please refer to ros.org for more information about installing and using ROS.

Please direct these kinds of questions to the [ROS Answers](answers.ros.org) forum in the future!  This place is for bug reporting, not tutorials.

**Comment by wjwwood** [comment]
Thanks @lucbettaieb, I'll just add that the rviz tutorials are here: http://wiki.ros.org/rviz/Tutorials
