### ISSUE TITLE
this commit cause some interactive marker not working 

### ISSUE THREAD

**Issue by zhuyiif** [ros-visualization/rviz#1178]
this commit may be cause something wrong, https://github.com/ros-visualization/rviz/commit/73ad3e122283b2a8cbd116bda0b2ccf63c3b03e7,
after I update rviz ,some interactive markers not working, even official tutorial e.g https://github.com/ros-visualization/visualization_tutorials.

**Comment by rhaschke** [comment]
Indeed this breaks interactive markers of MoveIt! as well. Previously, rviz was sloppy about unnormalized unit quaternions. Now it rejects those markers. It would be nice to have a smooth transition phase, where a warning is generated, the quaternion is normalized and processed anyway.

**Comment by rhaschke** [comment]
Actually, the offending PR is #1167.

**Comment by zhuyiif** [comment]
thanks for quick response :)

**Comment by rhaschke** [comment]
The problem is fixed and a release candidate is available via [ros-shadow-fixed](http://wiki.ros.org/ShadowRepository).

**Comment by wjwwood** [comment]
Closing this assuming the issue was actually fixed by now. Please comment if that's not the case.
