### ISSUE TITLE
pointcloud display in rviz2 for ros 2

### ISSUE THREAD

**Issue by sagniknitr** [ros-visualization/rviz#1190]
I have created a demo node which publishes the point cloud data from .pcd file in a senosr_msgs/PointCloud2 format.The rviz tool for ros 2 is able to detect the pointcloud topic name, but it is coming under unvisualizable topic.

Is there any way where I can visualize the sensor_msgs/PointCloud data in ROS2 environment ?

**Comment by dhood** [comment]
Please ask this question on https://github.com/ros2/rviz/issues where they will be able to inform you of the state of rviz in ROS 2
