### ISSUE TITLE
meshes of RobotLinks are not cached and reused?

### ISSUE THREAD

**Issue by rhaschke** [ros-visualization/rviz#1222]
When enabling the robot train in MoveIt's MotionPlanning plugin, I observe a dramatic increase of memory usage that is linear with the number of steps in the trail. However, all these visualizations use the same meshes and they should be reused. Obviously they are not. In my case, with a complex robot model, my machine memory of 12GByte is exhausted already with >650 trail steps.

**Comment by dhood** [comment]
Visualisations using `loadMeshFromResource` will [reuse existing meshes](https://github.com/ros-visualization/rviz/blob/7970ba08cee3810cfa1609c3b0f5136970eb2f7c/src/rviz/mesh_loader.cpp#L660). For example, [in the mesh marker test](https://github.com/ros-visualization/rviz/blob/1e1e96d0f28f115b90136a79386f0e6f48d23bae/src/test/mesh_marker_test.cpp#L69), multiple markers are published with the same resource but the mesh is only loaded once. 
Robot links [also use `loadMeshFromResource`](https://github.com/ros-visualization/rviz/blob/4c8793b634f810721e5c590f260169940b7f301f/src/rviz/robot/robot_link.cpp#L598).

To understand what is different in your situation could you give some additional context?
What visualisation type is the MotionPlanning plugin? Can you create a reproducible example using one of the default plugins? Is there a chance that it's the moveit plugin itself that's not re-using meshes, or have you ruled that out already?

**Comment by rhaschke** [comment]
The MotionPlanning plugin instantiates multiple `rviz::Robots` to yield a trail of the robot trajectory. Maybe it's not the meshes but the numerous geometry primitives that create their own meshes over and over...
What about all the other members in rviz::Robot, e.g. selection? Do the consume lots of memory?

**Comment by simonschmeisser** [comment]
Do you have attached objects? Those are unfortunately not cached. Also robot markers do some strange thinks when you have more than one mesh in a link. But I'm sure there are further places that could be optimized ...

**Comment by rhaschke** [comment]
I don't have attached objects. I think, there should be a lightweight `RobotTrail` class in `rviz`, derived from `rviz::Robot` to explicitly share all data between different robot visualizations along the trail.

**Comment by simonschmeisser** [comment]
I can confirm this, adding a moveit_ros_visualization/Trajectory and enabling "Show Trail" will increase memory usage by about 40Mb for a "normal sized" robot. It is a MoveIt! based plugin though ... maybe we should track it there?

**Comment by rhaschke** [comment]
As I said, the MoveIt plugin simply allocates `rviz::Robot` instances for each trail point.
Manually adding `RobotModel` displays I also see an increase of a few Mb per instance. 
Curiously, this memory is *not* freed when removing the `RobotModel` instances! This indicates a leak in `RobotModel`.
In MoveIt we continously allocate and free Robot instances...

**Comment by a-price** [comment]
Not sure if this should go here or in the MoveIt plugin, but there appears to be a significant memory leak when using the `moveit_ros_visualization/Trajectory` plugin. Each of the memory stairsteps below corresponds to sending a new `DisplayTrajectory` to RViz

![screenshot from 2018-08-11 14-36-48](https://user-images.githubusercontent.com/3324751/43995051-311f3b22-9d75-11e8-98df-5ea951a00ed1.png)

![screenshot from 2018-08-11 14-37-50](https://user-images.githubusercontent.com/3324751/43995059-5dba9c12-9d75-11e8-8596-1d9a9ba58f56.png)

The trajectories are for a couple of Kuka IIWA-7's with 150 steps per trajectory.

**Comment by rhaschke** [comment]
@wjwwood @dhood How can we progress on this issue?

**Comment by rhaschke** [comment]
I tracked this issue down to the Material handling in `rviz::Robot`. Although, the material is stored as a SharedPtr, it's not actually freed, because another pointer instance is held by the `MaterialManager`.
If I will find some time next week, I will propose a PR to fix the issue.
