### ISSUE TITLE
rviz 1.12.13 aborting with create class exception

### ISSUE THREAD

**Issue by amarnathbana** [ros-visualization/rviz#1225]
Hi,
Yesterday I updated ros using sudo apt-get dist-upgrade to install opencv in my system.
After that,when i try to add laserscan or point cloud to displays rviz is shutting down with following error:

```
[ INFO] [1524269660.368092157]: rviz version 1.12.13
[ INFO] [1524269660.368130865]: compiled against Qt version 5.5.1
[ INFO] [1524269660.368139750]: compiled against OGRE version 1.9.0 (Ghadamon)
[ INFO] [1524269660.522309417]: Stereo is NOT SUPPORTED
[ INFO] [1524269660.522468379]: OpenGl version: 3 (GLSL 1.3).
terminate called after throwing an instance of 'pluginlib::CreateClassException'
  what():  MultiLibraryClassLoader: Could not create class of type rviz::MONO8PCTransformer
Aborted (core dumped)
```
I am using Kinetic and Ubuntu 16.04

**Comment by dhood** [comment]
could you try updating all ROS packages (you should get 1.12.15 for rviz on kinetic).

**Comment by wjwwood** [comment]
I'll close for now, feel free to report back if this is still an issue and I can reopen.
