### ISSUE TITLE
error: ‘class tf::TransformListener’ has no member named ‘getTF2BufferPtr’

### ISSUE THREAD

**Issue by wmx-github** [ros-visualization/rviz#1241]
In file included from /home/wmx/myWorkSpace/ros_ws/src/rviz/src/rviz/frame_manager.cpp:30:0:
/home/wmx/myWorkSpace/ros_ws/src/rviz/src/rviz/frame_manager.h: In member function ‘const std::shared_ptr<tf2_ros::Buffer> rviz::FrameManager::getTF2BufferPtr()’:
/home/wmx/myWorkSpace/ros_ws/src/rviz/src/rviz/frame_manager.h:243:74: error: ‘class tf::TransformListener’ has no member named ‘getTF2BufferPtr’
   const std::shared_ptr<tf2_ros::Buffer> getTF2BufferPtr() { return tf_->getTF2BufferPtr(); }

**Comment by wjwwood** [comment]
Please take more time to properly format your questions and add more details, like how you produced this error.

Also please ask questions on answers.ros.org, see: https://wiki.ros.org/Support

----

You need to make sure you're using the right version of ROS with `rviz`. The `melodic-devel` branch needs a newer version of `tf` than you are using.

**Comment by theg4sh** [comment]
> You need to make sure you're using the right version of ROS with rviz.

True, but currently release version 1.13.1 does not compile with fresh ros-kinetic. I did upgrade Ubuntu packages today and then attempt to recompile rviz, but got the same error as in the subject message.

Pretty formatted error:
```Scanning dependencies of target rviz
[  1%] Building CXX object src/rviz/CMakeFiles/rviz.dir/bit_allocator.cpp.o
[  1%] Building CXX object src/rviz/CMakeFiles/rviz.dir/config.cpp.o
[  1%] Building CXX object src/rviz/CMakeFiles/rviz.dir/display.cpp.o
[  2%] Building CXX object src/rviz/CMakeFiles/rviz.dir/display_factory.cpp.o
[  2%] Building CXX object src/rviz/CMakeFiles/rviz.dir/display_group.cpp.o
[  2%] Building CXX object src/rviz/CMakeFiles/rviz.dir/displays_panel.cpp.o
[  3%] Building CXX object src/rviz/CMakeFiles/rviz.dir/failed_display.cpp.o
[  3%] Building CXX object src/rviz/CMakeFiles/rviz.dir/failed_panel.cpp.o
[  5%] Building CXX object src/rviz/CMakeFiles/rviz.dir/failed_tool.cpp.o
[  5%] Building CXX object src/rviz/CMakeFiles/rviz.dir/failed_view_controller.cpp.o
[  5%] Building CXX object src/rviz/CMakeFiles/rviz.dir/frame_manager.cpp.o
In file included from /home/t4g/repos/cnord/opt/rviz/src/rviz/frame_manager.cpp:30:0:
/home/t4g/repos/cnord/opt/rviz/src/rviz/frame_manager.h: In member function ‘const std::shared_ptr<tf2_ros::Buffer> rviz::FrameManager::getTF2BufferPtr()’:
/home/t4g/repos/cnord/opt/rviz/src/rviz/frame_manager.h:243:74: error: ‘class tf::TransformListener’ has no member named ‘getTF2BufferPtr’
   const std::shared_ptr<tf2_ros::Buffer> getTF2BufferPtr() { return tf_->getTF2BufferPtr(); }
```

**Comment by rhaschke** [comment]
The 1.13.x release series is targeting Melodic. If you want to build the melodic-devel branch on Kinetic, you will also need to update tf2 to melodic-devel and build it together with rviz.
