### ISSUE TITLE
STL Files Always Appear to have 1769221948 Triangles

### ISSUE THREAD

**Issue by nkhldas** [ros-visualization/rviz#1244]
I'm trying to create a visualization marker in rviz `1.12.15`. Despite which binary STL file I specify in the `mesh_resource` field, I receive the following error every time I publish the marker:

```
[ERROR] [1526316491.059221183]: The STL file 'src/cube.stl' is malformed. According to the binary STL header it should have '1769221948' triangles, but it has too little data for that to be the case.
[ERROR] [1526316491.059279702]: Failed to load file [src/cube.stl]
```

Attached are two example STL files (cube.stl and duck.stl) which should have 12 and 10960 triangles, respectively. However, 1769221948 triangles are always detected by the STL reader when specifying the 'mesh_resource' field. Any advice on how I can resolve this?

[STL_examples.zip](https://github.com/ros-visualization/rviz/files/2001821/STL_examples.zip)

**Comment by rhaschke** [comment]
Having switched to the default assimp loader in #1365, I don't observe such an issue anymore.
