### ISSUE TITLE
RVIZ-1.13.1 crashed with OGRE-1.10.11-4

### ISSUE THREAD

**Issue by ziokuroi** [ros-visualization/rviz#1259]
Arch Linux with ROS Melodic.
LOG:

> [ziokuroi@zeta ~]$ rosrun rviz rviz
[ INFO] [1529071253.148222721]: rviz version 1.13.1
[ INFO] [1529071253.148245000]: compiled against Qt version 5.11.0
[ INFO] [1529071253.148256770]: compiled against OGRE version 1.10.11 (Xalafu)
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
[ INFO] [1529071253.474469837]: Stereo is NOT SUPPORTED
[ INFO] [1529071253.475217752]: OpenGl version: 3 (GLSL 1.3).
[ERROR] [1529071253.475333574]: ItemIdentityException: Resource with the name BaseWhiteNoLighting already exists. in ResourceManager::add at /home/ziokuroi/ogre/repos/community-x86_64/src/ogre-1.10.11/OgreMain/src/OgreResourceManager.cpp (line 158)
terminate called after throwing an instance of 'Ogre::ItemIdentityException'
  what():  ItemIdentityException: Resource with the name BaseWhiteNoLighting already exists. in ResourceManager::add at /home/ziokuroi/ogre/repos/community-x86_64/src/ogre-1.10.11/OgreMain/src/OgreResourceManager.cpp (line 158)
Aborted (core dumped)

**Comment by wjwwood** [comment]
I believe this was already reported and fixed in https://github.com/ros-visualization/rviz/pull/1105. I'll close this, comment if you do not believe this is the case.
