### ISSUE TITLE
Starting rviz in fullscreen

### ISSUE THREAD

**Issue by davidbsp** [ros-visualization/rviz#1260]
Is there an option to start rviz in fullscreen (cmd line args or via saved configuration file) ?

**Comment by zaid-g** [comment]
Looking for the same thing. Hope someone has an answer

**Comment by VictorLamoine** [comment]
There is no way right now, full screen was added in this merge request: https://github.com/ros-visualization/rviz/pull/1017/files

There is a menu and a shortcut only at the moment

**Comment by rhaschke** [comment]
Fixed via #1413: new --fullscreen cmdline option.

**Comment by edgariph98** [comment]
how would I be able to set the configuration to be full screen?

**Comment by rhaschke** [comment]
> how would I be able to set the configuration to be full screen?

@edgariph98, as written in the previous post (and document with `--help`):
`rviz --fullscreen`

**Comment by edgariph98** [comment]
> > how would I be able to set the configuration to be full screen?
> 
> @edgariph98, as written in the previous post (and document with `--help`): `rviz --fullscreen`

is there a way to set a flag from a config.rviz file to start the rviz in full-screen mode? I am currently loading the rviz visualization frame into a window and I only want to see the rendering window, is there another way to achieve this instead of full-screen mode?

**Comment by rhaschke** [comment]
No, I don't think so.
