### ISSUE TITLE
Disable compiler predefs to allow ccache build support

### ISSUE THREAD

**Issue by ahoarau** [ros-visualization/rviz#1261]
Building with `CXX="ccache g++"` `CC="ccache gcc"`, I get the following error : 
```
AutoMoc subprocess error
------------------------
The content generation command for "moc_predefs.h" failed.
```
This is a conflict between Qt cmake macros and ccache.
Discussed here : https://gitlab.kitware.com/cmake/cmake/issues/17275

It can be easily fixed with this patch :

```patch
diff --git a/CMakeLists.txt b/CMakeLists.txt
index da590a1..340e4c5 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -100,6 +100,9 @@ find_package(OpenGL REQUIRED)
 
 set(CMAKE_AUTOMOC ON)
 set(CMAKE_INCLUDE_CURRENT_DIR ON)
+set(CMAKE_AUTOMOC_COMPILER_PREDEFINES OFF)
+set(CMAKE_AUTOUIC ON)
+set(CMAKE_AUTORCC ON)
 
 option(UseQt5 "UseQt5" ON)
 if (UseQt5)
```

Same for the visualisation_tutorials pkg.

NOTE : Only `set(CMAKE_AUTOMOC_COMPILER_PREDEFINES OFF)` is strictly necessary, `CMAKE_AUTOUIC` and `CMAKE_AUTORCC` are just here to make sure of their values

**Comment by rhaschke** [comment]
Usually `ccache` provides symlinks in /usr/lib/ccmake. If you put this into your path, `ccache` is used just fine without extra effort.
