### ISSUE TITLE
RobotModel doesn't show mesh if URDF parameter only becomes available after rviz loads

### ISSUE THREAD

**Issue by asymingt** [ros-visualization/rviz#1279]
There is a quirk with RobotModel in the kinetic version of rviz, which only presents itself when (a) you have saved an rviz config file with a RobotModel, and (b) run rviz before the URDF description of the robot model is available. If you want to separate into two different launch files -- one for starting a simulation and the other for spawning a model -- and your robot description is declared in your spawn launch file, then this is a problem. If you robot URDF is generated from arguments specified to the spawn launch file, it is not possible to move the URDF parameter declaration to the other launch file.

A simple, but cumbersome, workaround is to toggle the visibility of the RobotModel in the rviz displays tab after spawning a model, which forces the URDF ROS parameter to be refreshed. It would be much more convenient to have a background timer do this for you.

**Comment by rhaschke** [comment]
Implemented via d171d8239.
