### ISSUE TITLE
Nothing display after only change the view pitch.

### ISSUE THREAD

**Issue by Zander-yang** [ros-visualization/rviz#1286]
I have drawn some strip lines in the rviz. When I move around with the mouse, sometimes the display area is all black. Is there any bugs in rviz? Or problems with my environment? I use a vm in my MacBook. The ubuntu version is 16.04. I will appreciate for any answers. Thanks a lot.
Bellowing screen prints show the problem. I only change the view pitch with keyboard input.
<img width="1680" alt="screen shot 2018-08-27 at 16 46 58" src="https://user-images.githubusercontent.com/35528136/44651099-0173b800-aa1b-11e8-8f9f-d346dc77a288.png">
<img width="1680" alt="screen shot 2018-08-27 at 16 46 38" src="https://user-images.githubusercontent.com/35528136/44651107-09335c80-aa1b-11e8-976c-1f14d4d58731.png">
<img width="1680" alt="screen shot 2018-08-27 at 16 47 21" src="https://user-images.githubusercontent.com/35528136/44651109-0c2e4d00-aa1b-11e8-96c0-56edb906573d.png">

**Comment by wjwwood** [comment]
I believe this is a duplicate of https://github.com/ros-visualization/rviz/issues/987 and in the past has been related to having very large transforms (using UTM zero as the world origin, for example). Please close this and add information to the other issue if you agree that it's a duplicate.

**Comment by Zander-yang** [comment]
@wjwwood Thank you so much. It is actually a duplicate of #987 . I changed the frame to make the coordinates value small. It worked!
