### ISSUE TITLE
RViz at 2fps within Docker container, mandatored to use Nouveau driver

### ISSUE THREAD

**Issue by moucrob** [ros-visualization/rviz#1322]
Hi, running RViz from a docker, it goes at 2fps maximum, is it normal?

I tried `roscore` + `rosrun rviz rviz` outside the docker, that is on the host machine, and it runs flawlessly at 20+ fps. 
- Note though that in docker I have an arm displayed in RViz (completely static though) whereas RViz' scene is completely empty when launched via rosrun on the host machine.
- Note also that I cannot use proprietary drivers (the machine embeds a geforce 1080 gtx), only Nouveau open source drivers for Nvidia, as otherwise RViz isn't launchable anymore (at least from docker) because of this error : 
```shell
libGL error: No matching fbConfigs or visuals found libGL
error: failed to load driver: swrast 
Could not initialize OpenGL for RasterGLSurface, reverting to RasterSurface.
```
- Also, currently using multiple monitors, it seems that nvidia proprietary drivers aren't compatible with displaylink ones...
- Having read [somewhere](http://wiki.ros.org/rviz/Troubleshooting) (paragraph 4.) that RViz anyway doesn't like multiscreens setups, I did try to move its window on each of the 3 monitors, and it is not better on the primary monitor...

**So could I speed up the framerate of RViz used from Docker while keeping my Nouveau driver config ?**

Otherwise, would you know how to get rid of these errors ? ([this guy](https://github.com/diegoferigo/dockerfiles/issues/6#issuecomment-457301619) seems to have managed to summon RViz from docker, but I don't know how to append those three lines to the docker files...)

**Comment by rhaschke** [comment]
Please see [here](http://wiki.ros.org/docker/Tutorials/Hardware%20Acceleration) and this script: [gui-docker](https://github.com/ros-planning/moveit/blob/master/.docker/gui-docker) for nvidia support.
