### ISSUE TITLE
Error: using typedef-name ‘Ogre::Vector3’ after ‘class’  class Vector3;

### ISSUE THREAD

**Issue by E-pep** [ros-visualization/rviz#1328]
Hello newbie here,

When i catkin_make my workspace, I get:
Error: using typedef-name ‘Ogre::Vector3’ after ‘class’ class Vector3;

It seems to be a problem with OGRE together with rviz. Can someone help?

**Comment by chapulina** [comment]
Hi @E-pep, welcome! Questions like these are better suited for https://answers.ros.org, see: https://wiki.ros.org/Support .

When you post a question there, try to add as many details as possible, like which steps you took to set up your workspace.

Good luck!
