### ISSUE TITLE
Remove signals from find_packages()?

### ISSUE THREAD

**Issue by jwhendy** [ros-visualization/rviz#1343]
Is [this issue](https://github.com/ros/ros_comm/pull/1580) also relevant here?

I'm building on arch linux with cmake 3.13 and boost 1.69 and get the same error. When removing [this line](https://github.com/ros/ros_comm/pull/1580)  from `CMakeLists.txt`, I'm able to build.

**Comment by rhaschke** [comment]
Thanks for pointing out this issue. I filed a fix for this: #1344. Could you please verify that this resolves your issue? I don't have a system with boost 1.69 available right now.
