### ISSUE TITLE
regression introduced in Debian Stretch

### ISSUE THREAD

**Issue by rhaschke** [ros-visualization/rviz#1352]
#1317 introduced a [regression on Debian Stretch](http://build.ros.org/job/Mbin_ds_dS64__rviz__debian_stretch_amd64__binary/27/display/redirect), which obviously doesn't provide `tinyxml2::XMLDocument::ErrorStr()` yet. I see two options:
- simple: remove the verbatim error string output, but only report the error code
- more elaborate: distinguish available tinyxml2 versions and selectively use `ErrorStr` or not.

@wjwwood, which option do you prefer?

**Comment by wjwwood** [comment]
Sorry, my answer was subtle, but in approving #1354 I implicitly was voting for the simple option.
