### ISSUE TITLE
Source code compilation failed

### ISSUE THREAD

**Issue by Zangpuzhuo** [ros-visualization/rviz#1353]
My environment is ROS(kinetic) + ubuntu16.04 + catkin(workspace),
I git rviz source: https://github.com/ros-visualization/rviz.git

when I run "catkin_make" in my catkin_ws(workspace) , error：
![image](https://user-images.githubusercontent.com/41785681/54407563-4215f300-4719-11e9-843c-14e30a80f27d.png)
Please tell me what should I do， thanks

**Comment by rhaschke** [comment]
You are trying to build the melodic-devel branch of rviz on Kinetic, which also requires an updated tf library (> 1.12.0). Either build the kinetic-devel branch or update required dependencies as well.

**Comment by Zangpuzhuo** [comment]
thanks very much.Your answer helps me a lot!
