### ISSUE TITLE
Error output loading e.g. 3ds meshes

### ISSUE THREAD

**Issue by dseifert** [ros-visualization/rviz#1366]
Due to the merge of #1317 (subsequently changed in #1352), I am now seeing the following error for my 3ds meshes when using rviz 1.13.3 in ROS Melodic on Ubuntu 18.04:

`[ERROR] [1554754289.703535903, 1.974491951]: /rviz: XML parse error [package://my_package/meshes/fancy_mesh.3ds]: XML_ERROR_PARSING_TEXT`

Reason: `loadMeshFromResource` calls `meshFromAssimpScene` for 3ds files, and then subsequently `getMeshUnitRescale` is called even if the file is not a Collada XML file.

**Comment by J-Rojas** [comment]
I have the same error for OBJ mesh files.

**Comment by rhaschke** [comment]
Addressed in #1365.
