### ISSUE TITLE
Camera display type crashes rviz (Melodic) when deselected or deleted

### ISSUE THREAD

**Issue by ashnap123** [ros-visualization/rviz#1372]
Camera display type crashes rviz when it it deselected or deleted. Recreated with multiple cameras on multiple machines.

### To recreate 
- Add any camera with a valid calibration
![rviz_add camera](https://user-images.githubusercontent.com/16392756/56893388-6ab03d00-6a7a-11e9-9357-931ec8cf42a2.png)

- Camera display image should be displayed with overlay
![rviz_camer_active](https://user-images.githubusercontent.com/16392756/56893414-77349580-6a7a-11e9-89ec-fd4daf9f02c8.png)

- Either delete or de-select Camera display to cause crash.
![rviz_crash](https://user-images.githubusercontent.com/16392756/56893549-f629ce00-6a7a-11e9-8bec-b9846a9de5bd.png)

### Your environment
* OS Version: Ubuntu 18.04
* ROS Distro: Melodic
* RViz, Qt, OGRE, OpenGl version as printed by rviz:
    rviz version 1.13.3
    compiled against Qt version 5.9.5
    compiled against OGRE version 1.9.0 (Ghadamon)
    Stereo is NOT SUPPORTED
    OpenGl version: 4.6 (GLSL 4.6).
    
* Console output
```
Gtk-Message: 12:27:56.341: GtkDialog mapped without a transient parent. This is discouraged.
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'
  what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argument
[1]    25031 abort (core dumped)  rviz
```

* Install type 
    Aptitude

**Comment by mcsheehan** [comment]
I'd like to bump this as a fairly major issue. The program crashes on moving camera windows around.

**Comment by rhaschke** [comment]
Upstream issue: https://github.com/ros/geometry2/pull/402.

**Comment by tsukione** [comment]
after 25d2c81cfd6a8660a7dfb953cfd67e5659cbeede this issue reappear @rhaschke
