### ISSUE TITLE
upgrade to tf2

### ISSUE THREAD

**Issue by jschleicher** [ros-visualization/rviz#1376]
tf has been deprecated since ROS Hydro. Please remove dependencies on tf for noetic. Only have dependencies on tf2 instead.

Maybe the existing work for ROS 2 can be backported?

**Comment by rhaschke** [comment]
I fully agree that it would be nice to replace tf with tf2. However, given the fact that nobody from the community _actively_ maintains this project anymore, we need to hope for volunteers to actually realize this cleanup.

**Comment by rhaschke** [comment]
Finished with #1498.
