### ISSUE TITLE
For collada meshes alpha of multiple RobotModel interfere

### ISSUE THREAD

**Issue by simonschmeisser** [ros-visualization/rviz#1385]
We noticed today that adding a second RobotModel display (or derived MoveIt ones) with alpha = 0.2 changes the display of the primary RobotModel to also have transparency. This only happens for Collada meshes, not STL

I first enable one RobotModel with alpha = 1, the robot uses individual collada meshes while gripper and camera are stl meshes

![image](https://user-images.githubusercontent.com/372442/61137408-bc873180-a4c5-11e9-9544-e165326b2aea.png)

now I enabled a second RobotModel where alpha=0.2 and it will (visually) override the value for both (the input field is not affected)

![image](https://user-images.githubusercontent.com/372442/61137444-d45eb580-a4c5-11e9-99f4-500e835f72a1.png)

Notice how both robots now have alpha=0.2 except for the gripper and camera

I suspect this is due to non unique material names, any idea @rhaschke ?

### Your environment
* OS Version: Ubuntu 18.04
* ROS Distro: Melodic
* RViz, Qt, OGRE, OpenGl version as printed by rviz:
    ```
    [ INFO] [1562941360.215562081]: rviz version 1.13.3
[ INFO] [1562941360.215614003]: compiled against Qt version 5.9.5
[ INFO] [1562941360.215624573]: compiled against OGRE version 1.9.0 (Ghadamon)
[ INFO] [1562941360.431414141]: Stereo is NOT SUPPORTED
[ INFO] [1562941360.432597198]: OpenGl version: 3 (GLSL 1.3).
    ```

**Comment by rhaschke** [comment]
Could you please check whether the issue was introduced in #1294, i.e. validate the version before this merge?

**Comment by simonschmeisser** [comment]
![image](https://user-images.githubusercontent.com/372442/61142589-6f5c8d00-a4d0-11e9-9202-b8a7e4a25afd.png)

seems to have regressed after commit c7b2daa13f0a6bcd2b7824329c0f40857090d0bf  

I disabled some links from both RobotModels to show that two alpha values are supported
