### ISSUE TITLE
Did anybody get working RVIZ in RPi4? (Raspbian Buster)

### ISSUE THREAD

**Issue by FPSychotic** [ros-visualization/rviz#1389]
Before enter in more detail, to try filter this a little, somebody has rviz working with RPi4? 
Just make note there is an issue with libboost1.67 and libogre 1.19. Finally I got install it but now is giving a error with q5ct and segmetation fault.. 
if there is no positive answer I will detail this better as I cannot right now as I need reinstall the SO.
Sorry by my poor english

thank you!

**Comment by rhaschke** [comment]
Currently, we are using Ogre 1.9.0. There is an [open PR](https://github.com/ros-visualization/rviz/pull/1242) of people working on Ogre 1.11 compatibility.

**Comment by FPSychotic** [comment]
https://www.facebook.com/groups/353575658687628/permalink/369364973775363/
i made it work teo months ago
