### ISSUE TITLE
Not sure if the order of variable is correct?

### ISSUE THREAD

**Issue by danielwangksu** [ros-visualization/rviz#1392]
API says:
Vector3 (const Real fX, const Real fY, const Real fZ)

https://github.com/ros-visualization/rviz/blob/f9b357fdc0bfea5361e27b506059e62eab1f861b/src/rviz/ogre_helpers/arrow.cpp#L134

**Comment by rhaschke** [comment]
Directly above of this line is a comment explaining it:
`// Have to mangle the scale because of the default orientation of the cylinders`

I'm closing this for now. If you observed any concrete issue, please feel free to reopen.
