### ISSUE TITLE
Feature request: Color bar

### ISSUE THREAD

**Issue by Yeshasvitvs** [ros-visualization/rviz#1395]
Is there any color bar option, similar to [matlab colorbar](https://www.mathworks.com/help/matlab/ref/colorbar.html) to visualize messages on a topic ?

**Comment by rhaschke** [comment]
You should be more precise:
- Which type of message do you want to visualize?
  - For point clouds, there is a [corresponding display](http://wiki.ros.org/rviz/DisplayTypes/PointCloud) that allows coloring of depth, for example.
  - For [maps](http://wiki.ros.org/rviz/DisplayTypes/Map), there is a coloring option as well.
- How do you want to map your message onto color?

Also, probably better ask this question on https://answers.ros.org.
