### ISSUE TITLE
Can't control interactive markers 

### ISSUE THREAD

**Issue by Achllle** [ros-visualization/rviz#1398]
I'm using interactive markers along with obstacles in the planning scene and I can't control the markers when the planning scene (green) is turned on in the rviz menu or when the arrows in the same ray as the octomap voxels.
![markers](https://user-images.githubusercontent.com/14060847/62660904-4a6b0680-b924-11e9-8b44-6572f8197d5e.png)

I couldn't find in the documentation whether this is (lack of) a feature or a bug.

### Environment
* OS Version: Ubuntu 16.04
* ROS Distro: Kinetic
* RViz, Qt, OGRE, OpenGl version as printed by rviz:
    ```
    [ros.rviz]: rviz version 1.12.17
    [ros.rviz]: compiled against Qt version 5.5.1
    [ros.rviz]: compiled against OGRE version 1.9.0 (Ghadamon)
    [ros.rviz]: Stereo is NOT SUPPORTED
    [ros.rviz]: OpenGl version: 4.5 (GLSL 4.5).
    ```

**Comment by rhaschke** [comment]
This is a MoveIt related issue. So please, file an issue there.
As a MoveIt maintainer, I have to say that your issue description is not sufficient yet. Please provide more details: What kind of object you want to move with the marker? A planning scene object? The octomap?
