### ISSUE TITLE
InteractiveMarker: do not crash on unknown marker type

### ISSUE THREAD

**Issue by simonschmeisser** [ros-visualization/rviz#1418]
https://github.com/ros-visualization/rviz/blob/325e74cf3dc1bdd1db859beae88db85c926948c9/src/rviz/default_plugin/interactive_markers/interactive_marker_control.cpp#L93

should add a continue

**Comment by v4hn** [comment]
This is true, but also `nan` values in arbitrary fields, or otherwise incorrectly specified marker properties might entail crashes or exceptions.

It probably makes sense to `checkMarkerMsg` each entry and skip it (+ error message) when checking fails.

**Comment by simonschmeisser** [comment]
> It probably makes sense to `checkMarkerMsg` each entry and skip it (+ error message) when checking fails.

you're welcome :wink:

**Comment by rhaschke** [comment]
Fixed via b1fc2e6214341b69d8d6370479577d9dd90505c3.
