### ISSUE TITLE
`rviz -d xyz` could look for `~/.rviz/xyz.rviz` if xyz does not exist? [feature request]

### ISSUE THREAD

**Issue by v4hn** [ros-visualization/rviz#1420]
This is just a minor potential usability improvement I came up with recently.
I use `rviz -d /path/to/file.rviz` quite a lot these days, working on a machine with multiple users of rviz.

Of course, this can be automated in a number of ways already, creating a shell alias, scripts or setup a launch file, but why not support the use-case in RViz directly?

Would it be a welcome feature in RViz to complete `rviz -d xyz` to `rviz -d $HOME/.rviz/xyz.rviz` if the original `xyz` is no valid file?

**Comment by rhaschke** [comment]
Why not. If you have it prepared already, please file a PR.

**Comment by v4hn** [comment]
We work in different ways. :grinning: 
I tend to ask whether it makes sense to write a patch for upstream *before* I invest the time to do it. ;)
I just wrote a patch and filed it as #1422

**Comment by rhaschke** [comment]
Fixed via #1422.
