### ISSUE TITLE
how can i record what display in rviz to a video?

### ISSUE THREAD

**Issue by dahewujiang** [ros-visualization/rviz#1421]
hello, I have add some markers in my video and lidar data which rendering in rviz. Now I want to automaticlly record the rviz window as a video to make that the video is synchronized with my lidar data . But I donot know how to do that. ROS.org said cloud use the glc to record, but I cannot open the link and can not install glc in my computer. 
Anyone can help? Thanks a lot!

### environment
* OS Version: Ubuntu 16.04
* ROS Distro: Kinetic 
* RViz, Qt, OGRE, OpenGl version as printed by rviz:

**Comment by rhaschke** [comment]
I suggest using [recordmydesktop](https://wiki.ubuntuusers.de/recordMyDesktop/), which is available in Ubuntu as a standard application. Such a question should be directed to ros.answers.org in the future.
