### ISSUE TITLE
where can I find information\tutorials about how to write my_config.rviz configs

### ISSUE THREAD

**Issue by oMalyugina** [ros-visualization/rviz#1430]
I don't have a problem with rviz. I want to find information about .rviz format files (how I understood it is ini format). And I can't find it.

Could you help me with materials about this topic? My main questions: how can I edit this file, what has to be there, what can I delete.

for example: google cartographer's demo_3d.rviz which I want to edit:
https://github.com/googlecartographer/cartographer_ros/blob/master/cartographer_ros/configuration_files/demo_3d.rviz

**Comment by rhaschke** [comment]
Please post such questions to https://answers.ros.org.
The best option to "edit" such files is to load them in rviz, modify there, and finally save again.
These files are not intended for manually editing.
