### ISSUE TITLE
Taking screenshot from ASTRA pro camera and saving it in folder

### ISSUE THREAD

**Issue by Azza71** [ros-visualization/rviz#1459]
I'm trying to take an image from the astra pro camera by using a voice command "capture". It takes the image and saves it in a folder in my ~/home/mxhra/FacialRecognition_Testing. Currently, I am able to take an image using the webcam and saving it to a folder to conduct facial recognition on the image, then removing the folder (to make it empty) and creating the same folder again (so there won't be more than 1 image in the folder at a time) using the following steps (which I have already fed into a python file, when the voice recognition hears the word "capture" it will do the following):

fswebcam -r 640x480 --jpeg 85 -D 1 --no-banner /home/mxhra/FacialRecognition_Testing/image.jpg
face_recognition ./FacialRecognition_Database/ ./FacialRecognition_Testing/
rm -r FacialRecognition_Testing
mkdir FacialRecognition_Testing

I would like to do the same thing but using an astra pro camera, which I have already created a workspace for and installed usb_cam to view the rgb-d output of the camera in RVIZ, please let me know if you can assist me in this.
I am using Linux Ubuntu 16.04 (Xenial) with ROS Kinetic.

**Comment by rhaschke** [comment]
I don't see how this is related to rviz. Please post your question at https://answers.ros.org.
