### ISSUE TITLE
Smooth rendering of spheres

### ISSUE THREAD

**Issue by wxmerkt** [ros-visualization/rviz#1461]
Hi!
I'd like to add support to display spheres with smoothing. I am using the OGRE built-in `PT_SPHERE` `PrefabType` to create a smooth sphere. However, unlike the `rviz_sphere.mesh` (radius 0.5), these are 100 units in radius by default. Using a scaling of `0.01`, I can get the desired behaviour for the marker array plug-in and robot link. Cf. example below:

### Before
![rviz_screenshot_2020_01_09-17_46_02](https://user-images.githubusercontent.com/1664508/72093698-d4246300-330c-11ea-8e5b-ee1abd6f9f4d.png)

### After
![rviz_screenshot_2020_01_09-17_49_14](https://user-images.githubusercontent.com/1664508/72093712-d8e91700-330c-11ea-9e50-a24009543039.png)

### Question
The issue for which I am looking input is how to add this persistently for all plug-ins that may create a `rviz::Shape::Sphere`. If I were to set the scale in `createEntity`, it can easily be overridden by a call to `setScale` from anywhere else. Obviously, I do not want to simply change the convention to avoid breaking plug-ins.

1. Is there a good solution to this I may have overlooked?
2. I believe another solution would be to update the `rviz_sphere.mesh` file. Would this be acceptable?

Many thanks for your input,
Wolfgang

**Comment by rhaschke** [comment]
I would suggest to update rviz_sphere.mesh, but maybe @wjwwood as another suggestion.

**Comment by wjwwood** [comment]
I don't have a better suggestion. How would you change the mesh file?

**Comment by wxmerkt** [comment]
@wjwwood please have a look at #1463 :-)
