### ISSUE TITLE
rviz.exe does not work on Win 10

### ISSUE THREAD

**Issue by PackChinoros** [ros-visualization/rviz#1470]
I've just installed ROS on Win10 and then I installed rviz but I cound not run it.

### Your environment
* OS Version: `win10`
* ROS Distro: `Melodic`
* RViz, Qt, OGRE, OpenGl version as printed by rviz:
    ``` ~ pip list
rviz version: 1.13.3
Qt version: 5.9.5
OGRE version 4.6.0
PyOpenGl version 3.1.5
    ```
![RVIZ ERROR](https://user-images.githubusercontent.com/55238898/74089661-2b694f00-4ad6-11ea-8663-e9ee059ce18a.jpg)

Moreover, I tried to check rviz version

![RVIZ ERROR2](https://user-images.githubusercontent.com/55238898/74098714-dd902d80-4b4d-11ea-9aff-4bfaa7210a11.jpg)

ERROR[rviz]: No definition of [rosunit] for OS [windows]

**Comment by rhaschke** [comment]
@seanyen, can you comment on this?

**Comment by seanyen** [comment]
@PackChinoros from the error messages "The procedure entry could not be located", it most likely there are some binaries version mismatched in your environment. Did you upgrade from a older install to a newer one?

You can try to nuke this folder `c:\opt\ros\melodic\x64\` and run `choco upgrade ros-melodic-desktop_full -y --force  --execution-timeout=0` again. If it doesn't help, I would suggest you to follow the instructions of `Uninstall` and then do `Binary Package Installation` again from this ROS [Wiki](http://wiki.ros.org/Installation/Windows).

**Comment by PackChinoros** [comment]
Thanks for getting back to me, I've already uninstalled then I tried to use ubuntu on WSL but another problem raise as OpenGL could not detect so I deleted everything and utilize VMware instead. Now, everything works well!
