### ISSUE TITLE
[Documentation] Build instructions

### ISSUE THREAD

**Issue by rubyFeedback** [ros-visualization/rviz#1472]
So I was just reading:

https://wiki.alopex.li/LetsBeRealAboutDependencies

Could build instructions be added to rviz? That way people like that blog author would not be able to claim that compiling rviz is hard (I don't know myself, trying to compile it right now, but he is right in one regards e. g. not INSTALL.md or similar file - perhaps someone could add a short file and link to it from the main README.md).

**Comment by rhaschke** [comment]
There _are_ generic build instructions available for ROS-based packages, namely catkin tutorials.
It doesn't make sense to build rviz (or any other ROS package) without a ROS environment as the author of the above blog post did. I don't think there is a need for action.
