### ISSUE TITLE
 The types of RViz (Converts rviz to dxf)

### ISSUE THREAD

**Issue by ftmzhrsckldr** [ros-visualization/rviz#1476]
Hello. The types of RViz application are very insufficient. So I want to make a plugin that converts rviz to dxf. Because I have to run the Rviz file to AutoCad. Do you think I can do this?

**Comment by rhaschke** [comment]
rviz doesn't have its own CAD file format. *.rviz files are just yaml files that save the configuration. So, I'm not quite sure what you want to do...
rviz essentially handles URDF files, which in turn can handle various CAD file types for meshes.
I guess for most of these types (if not all of them) exist various converters.

**Comment by ftmzhrsckldr** [comment]
Thank you for the quick reply. I have to use Rviz very often. Converters can be mixed and paid. I want to make a simple plugin. Thus, other people can also benefit.

**Comment by rhaschke** [comment]
You didn't yet answer, what you actually want to convert. *.rviz files do not make sense.

**Comment by ftmzhrsckldr** [comment]
yaml to dxf

**Comment by rhaschke** [comment]
*.rviz / yaml to dxf doesn't make sense, because these config files do not contain CAD data.

**Comment by ftmzhrsckldr** [comment]
Oki. Thanks for helping.
