### ISSUE TITLE
Feature: Publish Reset-Button and Many More

### ISSUE THREAD

**Issue by bugerry87** [ros-visualization/rviz#1484]
Does RViz publish any of its internal states?

ROS follows a publish/subscribe pattern, so why RViz does not?

Publish a message when:

- hit the 'Reset' button
- camera view changed
- a node got subscribed
- etc.

There are nodes which are mostly responsible for visualization. Or think about SLAM.
When I hit 'Reset' in rviz I would like to have the chance to also reset the internal states of my nodes, such that those can keep publishing a proper visualization.

**Comment by rhaschke** [comment]
rviz is intended to visualize the state of the ROS system, not to control it. As such it receives inputs only. You are free to write your own plugin to implement such behaviour.
