### ISSUE TITLE
Origin of new sphere marker has an offset

### ISSUE THREAD

**Issue by Levaru** [ros-visualization/rviz#1485]
I noticed that since the new commit 2cf0b247e81b82899b2616bee9008356b5ab0f62 the sphere marker has a light offset, most likely caused by a wrong origin when the mesh file was created.

You can barely see it in this screenshot, but it is quite noticeable in my application.
![rviz_screenshot_2020_03_31-11_06_53](https://user-images.githubusercontent.com/46074016/78008826-723e2d00-7340-11ea-9ca4-4c5e0a106204.png)

### My environment
* OS Version: e.g. Ubuntu 18.04
* ROS Distro: Melodic
* RViz, Qt, OGRE, OpenGl version as printed by rviz:
    ```
    [ INFO]: rviz version 1.13.7
    [ INFO]: compiled against Qt version 5.9.5
    [ INFO]: compiled against OGRE version 1.9.0 (Ghadamon)
    [ INFO]: Forcing OpenGl version 0.
    [ INFO]: Stereo is NOT SUPPORTED
    [ INFO]: OpenGl version: 3 (GLSL 1.3).
    ```

**Comment by rhaschke** [comment]
@wxmerkt, please can you have a look at this issue as you authored the original PR #1463.

**Comment by wxmerkt** [comment]
Yes, I will take a look at it.

**Comment by wxmerkt** [comment]
Please take a look at #1487 - I fixed the issue with the sphere being off centre.
