### ISSUE TITLE
RVIZ Segmentation Fault on WSL2 

### ISSUE THREAD

**Issue by malghooneh** [ros-visualization/rviz#1490]
I am running rosrun rviz rviz in WSL2 and keep getting "segmentation fault" .. 

![image](https://user-images.githubusercontent.com/26723222/79818092-f0e12580-8354-11ea-87b1-4e5095ae23bf.png)

### My environment is:
WSL2 (ubuntu 18.04) on windows 10
ROS Melodic

I have set VcXSrv on the windows side, and glxgears works fine ...

Any idea what else I can try?

**Comment by rhaschke** [comment]
See https://github.com/ros-visualization/rviz/issues/1491#issuecomment-619532542 for a possible answer. What is the difference between WSL ans WSL2?

**Comment by malghooneh** [comment]
> See [#1491 (comment)](https://github.com/ros-visualization/rviz/issues/1491#issuecomment-619532542) for a possible answer. What is the difference between WSL ans WSL2?

Thanks for the link. The main difference is Kernel. WSL 2 uses an entirely new architecture that uses a real Linux kernel.
