### ISSUE TITLE
Multiple RobotModel cannot listen to different transform topics

### ISSUE THREAD

**Issue by raphaeldeimel** [ros-visualization/rviz#1507]
Due to https://github.com/ros/robot_state_publisher/issues/125 robot_state publisher in noetic no longer supports prefixing transforms.

If one publishes more than one robot state using the same robot_description (say, for visualizing multiple poses of the same robot), those now need to be published on separate topics to distinguish them. But RobotModel does not have a parameter for specifying the topic to listen to. 

This is a regression / API breakage in robot_state_publisher between melodic and noetic, but it was supposedly introduced to bring noetic in line with how ROS2 works. 

Example use case: publish current and expected pose of a robot:
```
<launch>

  <param  name="robot_description" command="$(find robot_models)/urdf/robot.urdf />

  <node name="tf_publisher" pkg="robot_state_publisher" type="robot_state_publisher" >
    <remap from="/tf" to="tf" />
  </node>

  <node name="tf_publisher2" pkg="robot_state_publisher" type="robot_state_publisher">
    <remap from="/tf" to="tf_expected" />
    <remap from="joint_states" to="joint_states_expected"/>
  </node>
 
</launch>
```

One way to resolve this breakage could be to add a "topic" parameter to RobotModel (defaulting to /tf)

### Your environment
* OS Version: e.g. Ubuntu 20.04
* ROS Distro: [Noetic]
* RViz, Qt, OGRE, OpenGl version as printed by rviz:

```rviz version 1.14.0
compiled against Qt version 5.12.8
compiled against OGRE version 1.9.0 (Ghadamon)
Forcing OpenGl version 0.
Stereo is NOT SUPPORTED
OpenGl version: 4.6 (GLSL 4.6).```

**Comment by rhaschke** [comment]
This is not related to rviz, but to robot_state_publisher. I filed a PR to fix the issue there: https://github.com/ros/robot_state_publisher/pull/139.
