### ISSUE TITLE
Failed to save rviz config

### ISSUE THREAD

**Issue by darrenjkt** [ros-visualization/rviz#1515]
Describe your issue here and explain how to reproduce it.

When I change my rviz config, then click file > save config as > h2.rviz

```
    Failed to open /opt/ros/melodic/share/rviz/h2.rviz for writing.
```

I've tried reinstalling RViz using `sudo apt-get install --reinstall ros-melodic-rviz` but the issue still remains.

### Your environment
* OS Version: Ubuntu 18.04
* ROS Distro: Melodic
* RViz, Qt, OGRE, OpenGl version as printed by rviz:
```
[ INFO] [1591762597.218020280]: rviz version 1.13.12
[ INFO] [1591762597.218085425]: compiled against Qt version 5.9.5
[ INFO] [1591762597.218093680]: compiled against OGRE version 1.9.0 (Ghadamon)
[ INFO] [1591762597.221079106]: Forcing OpenGl version 0.
[ INFO] [1591762597.678897836]: Stereo is NOT SUPPORTED
[ INFO] [1591762597.678943111]: OpenGl version: 4.6 (GLSL 4.6).
```

**Comment by rhaschke** [comment]
Obviously, you don't have permission to write in `/opt/ros/melodic`!

**Comment by wangchen-1994** [comment]
hi,you can try to change folder to your work space,such as catkin_ws/

**Comment by AdamArena** [comment]
Such a monumentally helpful answer @rhaschke. Having encountered the same issue myself and now seeing your descriptive answer I know exactly how to proceed from here! Great!

**Comment by chanakatb** [comment]
> hi,you can try to change folder to your work space,such as catkin_ws/

Thanks. It works.
