### ISSUE TITLE
Address boundary error

### ISSUE THREAD

**Issue by dnstzzx** [ros-visualization/rviz#1538]
quit when launched
console:

> rviz
[ INFO] [1598185052.370867500]: rviz version 1.12.17
[ INFO] [1598185052.370925500]: compiled against Qt version 5.5.1
[ INFO] [1598185052.370957900]: compiled against OGRE version 1.9.0 (Ghadamon)
fish: 'rviz' terminated by signal SIGSEGV (Address boundary error)

OS Version:  Ubuntu 16.04
ROS Distro: Kinetic

>rviz -l
[ INFO] [1598185223.728808900]: rviz version 1.12.17
[ INFO] [1598185223.728876400]: compiled against Qt version 5.5.1
[ INFO] [1598185223.728884600]: compiled against OGRE version 1.9.0 (Ghadamon)
[ INFO] [1598185223.948563700]: Creating resource group General
[ INFO] [1598185223.948687500]: Creating resource group Internal
[ INFO] [1598185223.948728300]: Creating resource group Autodetect
[ INFO] [1598185223.948834100]: SceneManagerFactory for type 'DefaultSceneManager' registered.
[ INFO] [1598185223.949003700]: Registering ResourceManager for type Material
[ INFO] [1598185223.949062300]: Registering ResourceManager for type Mesh
[ INFO] [1598185223.949122200]: Registering ResourceManager for type Skeleton
[ INFO] [1598185223.949215800]: MovableObjectFactory for type 'ParticleSystem' registered.
[ INFO] [1598185223.949349600]: ArchiveFactory for archive type FileSystem registered.
[ INFO] [1598185223.949413800]: ArchiveFactory for archive type Zip registered.
[ INFO] [1598185223.949481300]: ArchiveFactory for archive type EmbeddedZip registered.
[ INFO] [1598185223.949550700]: DDS codec registering
[ INFO] [1598185223.949617500]: FreeImage version: 3.17.0
[ INFO] [1598185223.949685800]: This program uses FreeImage, a free, open source image library supporting all common bitmap formats. See http://freeimage.sourceforge.net for details
[ INFO] [1598185223.949851500]: Supported formats: bmp,ico,jpg,jif,jpeg,jpe,jng,koa,iff,lbm,mng,pbm,pbm,pcd,pcx,pgm,pgm,png,ppm,ppm,ras,tga,targa,tif,tiff,wap,wbmp,wbm,psd,cut,xbm,xpm,gif,hdr,sgi,rgb,rgba,bw,exr,j2k,j2c,jp2,pfm,pct,pict,pic,3fr,arw,bay,bmq,cap,cine,cr2,crw,cs1,dc2,dcr,drf,dsc,dng,erf,fff,ia,iiq,k25,kc2,kdc,mdc,mef,mos,mrw,nef,nrw,orf,pef,ptx,pxn,qtk,raf,raw,rdc,rw2,rwl,rwz,sr2,srf,srw,sti,x3f,webp,jxr,wdp,hdp
[ INFO] [1598185223.949910100]: PVRTC codec registering
[ INFO] [1598185223.950014200]: ETC codec registering
[ INFO] [1598185223.950087000]: Registering ResourceManager for type HighLevelGpuProgram
[ INFO] [1598185223.950163600]: Registering ResourceManager for type Compositor
[ INFO] [1598185223.950411700]: MovableObjectFactory for type 'Entity' registered.
[ INFO] [1598185223.950491200]: MovableObjectFactory for type 'Light' registered.
[ INFO] [1598185223.950566400]: MovableObjectFactory for type 'BillboardSet' registered.
[ INFO] [1598185223.950646300]: MovableObjectFactory for type 'ManualObject' registered.
[ INFO] [1598185223.950735100]: MovableObjectFactory for type 'BillboardChain' registered.
[ INFO] [1598185223.950808800]: MovableObjectFactory for type 'RibbonTrail' registered.
[ INFO] [1598185223.950951400]: *-*-* OGRE Initialising
[ INFO] [1598185223.951007100]: *-*-* Version 1.9.0 (Ghadamon)
[ INFO] [1598185223.951087500]: OverlayElementFactory for type Panel registered.
[ INFO] [1598185223.951146800]: OverlayElementFactory for type BorderPanel registered.
[ INFO] [1598185223.951208000]: OverlayElementFactory for type TextArea registered.
[ INFO] [1598185223.951295200]: Registering ResourceManager for type Font
[ INFO] [1598185223.951413300]: Loading library /usr/lib/x86_64-linux-gnu/OGRE-1.9.0/RenderSystem_GL
[ INFO] [1598185223.952809600]: Installing plugin: GL RenderSystem
[ INFO] [1598185223.952906500]: OpenGL Rendering Subsystem created.
[ INFO] [1598185223.956638500]: Plugin successfully installed
[ INFO] [1598185223.956725600]: Loading library /usr/lib/x86_64-linux-gnu/OGRE-1.9.0/Plugin_OctreeSceneManager
[ INFO] [1598185223.957556800]: Installing plugin: Octree Scene Manager
[ INFO] [1598185223.957619800]: Plugin successfully installed
[ INFO] [1598185223.957663200]: Loading library /usr/lib/x86_64-linux-gnu/OGRE-1.9.0/Plugin_ParticleFX
[ INFO] [1598185223.958516500]: Installing plugin: ParticleFX
[ INFO] [1598185223.958599200]: Particle Emitter Type 'Point' registered
[ INFO] [1598185223.958651100]: Particle Emitter Type 'Box' registered
[ INFO] [1598185223.958721600]: Particle Emitter Type 'Ellipsoid' registered
[ INFO] [1598185223.958783500]: Particle Emitter Type 'Cylinder' registered
[ INFO] [1598185223.958842000]: Particle Emitter Type 'Ring' registered
[ INFO] [1598185223.958894900]: Particle Emitter Type 'HollowEllipsoid' registered
[ INFO] [1598185223.958932400]: Particle Affector Type 'LinearForce' registered
[ INFO] [1598185223.958998300]: Particle Affector Type 'ColourFader' registered
[ INFO] [1598185223.959054000]: Particle Affector Type 'ColourFader2' registered
[ INFO] [1598185223.959119800]: Particle Affector Type 'ColourImage' registered
[ INFO] [1598185223.959181200]: Particle Affector Type 'ColourInterpolator' registered
[ INFO] [1598185223.959261400]: Particle Affector Type 'Scaler' registered
[ INFO] [1598185223.959326200]: Particle Affector Type 'Rotator' registered
[ INFO] [1598185223.959388000]: Particle Affector Type 'DirectionRandomiser' registered
[ INFO] [1598185223.959446200]: Particle Affector Type 'DeflectorPlane' registered
[ INFO] [1598185223.959501700]: Plugin successfully installed
[ INFO] [1598185223.959548400]: CPU Identifier & Features
[ INFO] [1598185223.959605700]: -------------------------
[ INFO] [1598185223.959664200]:  *   CPU ID: AuthenticAMD: AMD Ryzen 5 4600H with Radeon Graphics
[ INFO] [1598185223.959718400]:  *      SSE: yes
[ INFO] [1598185223.959772000]:  *     SSE2: yes
[ INFO] [1598185223.959826000]:  *     SSE3: yes
[ INFO] [1598185223.959878900]:  *      MMX: yes
[ INFO] [1598185223.959932600]:  *   MMXEXT: yes
[ INFO] [1598185223.959972600]:  *    3DNOW: no
[ INFO] [1598185223.960032800]:  * 3DNOWEXT: no
[ INFO] [1598185223.960073900]:  *     CMOV: yes
[ INFO] [1598185223.960116700]:  *      TSC: yes
[ INFO] [1598185223.960174900]:  *      FPU: yes
[ INFO] [1598185223.960276200]:  *      PRO: yes
[ INFO] [1598185223.960338500]:  *       HT: no
[ INFO] [1598185223.960393700]: -------------------------
[ INFO] [1598185223.960455600]: ******************************
*** Starting GLX Subsystem ***
******************************
[ INFO] [1598185223.960526600]: Registering ResourceManager for type Texture
[ INFO] [1598185223.960669300]: GLRenderSystem::_createRenderWindow "OgreWindow(0)", 1x1 windowed  miscParams: FSAA=4 contentScalingFactor=1.000000 externalGLControl= externalWindowHandle=3670017 parentWindowHandle=3670017
[ INFO] [1598185223.981360000]: GLXWindow::create used FBConfigID = 144
[ INFO] [1598185223.982791400]: GL_VERSION = 1.4 (4.6.13587 Compatibility Profile Context 19.40.34.04 26.20.14034.4001)
[ INFO] [1598185223.983229400]: GL_VENDOR = ATI Technologies Inc.
[ INFO] [1598185223.983594100]: GL_RENDERER = AMD Radeon(TM) Graphics
[ INFO] [1598185223.983724500]: GL_EXTENSIONS = GL_ARB_depth_texture GL_ARB_draw_buffers GL_ARB_fragment_program GL_ARB_fragment_program_shadow GL_ARB_imaging GL_ARB_multisample GL_ARB_multitexture GL_ARB_occlusion_query GL_ARB_point_parameters GL_ARB_point_sprite GL_ARB_shadow GL_ARB_shadow_ambient GL_ARB_texture_border_clamp GL_ARB_texture_compression GL_ARB_texture_cube_map GL_ARB_texture_env_add GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_filter_anisotropic GL_ARB_texture_mirrored_repeat GL_ARB_texture_non_power_of_two GL_ARB_texture_rectangle GL_ARB_transpose_matrix GL_ARB_vertex_program GL_ARB_window_pos GL_EXT_abgr GL_EXT_bgra GL_EXT_blend_color GL_EXT_blend_equation_separate GL_EXT_blend_func_separate GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_copy_texture GL_EXT_draw_range_elements GL_EXT_fog_coord GL_EXT_framebuffer_object GL_EXT_multi_draw_arrays GL_EXT_packed_pixels GL_EXT_point_parameters GL_EXT_rescale_normal GL_EXT_secondary_color GL_EXT_separate_specular_color GL_EXT_shadow_funcs GL_EXT_stencil_wrap GL_EXT_subtexture GL_EXT_texture3D GL_EXT_texture_compression_s3tc GL_EXT_texture_edge_clamp GL_EXT_texture_env_add GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_EXT_texture_filter_anisotropic GL_EXT_texture_lod GL_EXT_texture_lod_bias GL_EXT_texture_mirror_clamp GL_EXT_texture_object GL_EXT_texture_rectangle GL_EXT_vertex_array GL_ATI_draw_buffers GL_ATI_texture_env_combine3 GL_ATI_texture_mirror_once GL_ATIX_texture_env_combine3 GL_IBM_texture_mirrored_repeat GL_INGR_blend_func_separate GL_NV_blend_square GL_NV_texgen_reflection GL_NV_texture_rectangle GL_SGIS_generate_mipmap GL_SGIS_texture_border_clamp GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod GL_SGIX_shadow_ambient GL_SUN_multi_draw_arrays
[ INFO] [1598185223.983869300]: Supported GLX extensions: GLX_ARB_create_context GLX_ARB_create_context_profile GLX_ARB_fbconfig_float GLX_ARB_get_proc_address GLX_ARB_multisample GLX_EXT_fbconfig_packed_float GLX_EXT_import_context GLX_EXT_visual_info GLX_EXT_visual_rating GLX_MESA_copy_sub_buffer GLX_MESA_multithread_makecurrent GLX_OML_swap_method GLX_SGIS_multisample GLX_SGIX_fbconfig GLX_SGIX_pbuffer GLX_SGIX_visual_select_group GLX_SGI_make_current_read GLX_SGI_swap_control
[ INFO] [1598185223.983956100]: ***************************
[ INFO] [1598185223.984026200]: *** GL Renderer Started ***
[ INFO] [1598185223.984116000]: ***************************
fish: 'rviz -l' terminated by signal SIGSEGV (Address boundary error)

**Comment by rhaschke** [comment]
Do I assume correctly that you observe this crash on startup of rviz?
What is your OpenGL setup? Which card? Which libOpenGL? We have seen recently a lot of issues introduced by new rollouts of Mesa OpenGL.
Did you try enforcing a lower open gl version (`rviz --opengl 210`) or software rendering (`export LIBGL_ALWAYS_SOFTWARE=1`)? See #1508 for more hints.

**Comment by dnstzzx** [comment]
Yes, it crashes on the startup
It doses relates to opengl and i'd like to thank you to point it out
In fact i'm using ubuntu under WSL and VcXsrv as my x server
the solution is as simple as disabling wgl in VcXsrv, and it works
thanks for your help
