### ISSUE TITLE
rviz fails to transform frames with leading slashes

### ISSUE THREAD

**Issue by lauralindzey** [ros-visualization/rviz#1548]
I have a bagfile with PointCloud2 message in the /left/driver frame.
When I try to visualize these in rviz, I set the fixed frame to "/left/driver", but it automatically changes to "left/driver" after I type it in, and I get the error "Failed to transform from frame [/left/driver] to frame [left/driver]"

If I process the bagfile to change /left/driver to left/driver, it displays correctly.

I think this is the same error that is being asked about here: https://answers.ros.org/question/355595/rviz-tf-error-failed-to-transform-from-frame-map-to-frame-map/

### Your environment
* OS Version: Ubuntu 20.04
* ROS Distro: Noetic
* RViz, Qt, OGRE, OpenGl version as printed by rviz:
    ```
[ INFO] [1602544755.809240504]: rviz version 1.14.1
[ INFO] [1602544755.809284506]: compiled against Qt version 5.12.8
[ INFO] [1602544755.809296759]: compiled against OGRE version 1.9.0 (Ghadamon)
    ```

**Comment by rhaschke** [comment]
http://wiki.ros.org/tf2/Migration#Removal_of_support_for_tf_prefix: 
> `tf2` asserts that all frame_ids do not start with `/`.

I'm afraid you need to remap your bag file.
