### ISSUE TITLE
Drag and drop of panels does not allow side-by-side positioning

### ISSUE THREAD

**Issue by paland3** [ros-visualization/rviz#1552]
Hello, I have two custom panels in rviz (one camera and one image) which I would like to show side by side. I can easily rearrange them in a top bottom fashion or in separate tabs, but cannot make them in to a side by side layout. 

I can do this:
![rviz](https://user-images.githubusercontent.com/7983561/96560260-5d19f300-12be-11eb-8e2b-84339a155963.png)

**But I would like to have the two "camera" panel next to each other, horizontally. Is there a way to do this?**

### Your environment
* Ubuntu 18.04
* ROS Distro:  Melodic
* RViz, Qt, OGRE, OpenGl version as printed by rviz:

```
[ INFO] [1603181482.756307440]: rviz version 1.13.13
[ INFO] [1603181482.756420956]: compiled against Qt version 5.9.5
[ INFO] [1603181482.756462844]: compiled against OGRE version 1.9.0 (Ghadamon)
```

**Comment by rhaschke** [comment]
This is a limitation of Qt's DockWidgets: https://doc.qt.io/qt-5/qdockwidget.html#details.
On the left and right they can be stacked vertically, on the bottom and top, they can be stacked horizontally:

![image](https://user-images.githubusercontent.com/5376030/96561839-5d1af280-12c0-11eb-8218-be8a0cb3b7cb.png)

**Comment by paland3** [comment]
@rhaschke  Thanks, this works almost perfectly! (stacking them at the bottom). 

Is there a way to hide the main 3d window? I.e. to close/remove it all the way. See attached picture: cannot remove the bottom bar (3d window minimised as much as I can).
![rviz2](https://user-images.githubusercontent.com/7983561/96566161-82f6c600-12c5-11eb-99dd-e970ed55eda7.png)


When an image and the 3d window is stacked horizontally, I can minimise the 3d window completely:
![rviz3](https://user-images.githubusercontent.com/7983561/96566855-61e2a500-12c6-11eb-938c-ebfa19f37fdc.png)

I do not need the 3d view in this setup. Thanks again!

**Comment by rhaschke** [comment]
No, there is no way to hide the central widget. You could put one camera in the left dock and one in the right and then "hide" the central widget in between:
![image](https://user-images.githubusercontent.com/5376030/96571447-dd932080-12cb-11eb-885c-41b7ed355777.png)

**Comment by paland3** [comment]
Nice, thanks again!
