### ISSUE TITLE
Is it possible to pass parameters to rviz config file?

### ISSUE THREAD

**Issue by oym1994** [ros-visualization/rviz#1555]
Hello, 
I have saved a rviz config file, some of its content are as below:
.
.
 Global Options:
    Background Color: 48; 48; 48
    Default Light: true
    Fixed Frame: Client0
    Frame Rate: 30
.
.
.

Now I want to launch rviz via .launch file and want to change the parameter of "Fixed Frame" in launch file(Instead of changing it on rviz panel). How can I do that?
Thank for your attention, hope to get any response!

**Comment by rhaschke** [comment]
Sorry, there is no way to override certain parameters in the config file. Just save another config file and load this one.
