### ISSUE TITLE
Unable to extract cylinder from point-cloud

### ISSUE THREAD

**Issue by abhyudit309** [ros-visualization/rviz#1556]
I'm following the move-it tutorials for melodic. In the Perception pipeline tutorial, on running:
roslaunch moveit_tutorials detect_and_add_cylinder_collision_object_demo.launch
I get the Octomap in Rviz, but its not able to extract the cylinder from the point cloud.
Expected output:
![Screenshot from 2020-10-15 23-31-55](https://user-images.githubusercontent.com/71165429/96169076-3d41a280-0f3f-11eb-85d5-154012eff809.png)
My Output:
![Screenshot from 2020-10-15 23-28-50](https://user-images.githubusercontent.com/71165429/96169100-4468b080-0f3f-11eb-9c34-7b8ac6d6de86.png)
I also get an  error message in my terminal saying this:
![Screenshot from 2020-10-15 23-39-05](https://user-images.githubusercontent.com/71165429/96169400-a9bca180-0f3f-11eb-804c-b1062ec32dd1.png)
Can someone help me fix this issue ?

**Comment by rhaschke** [comment]
This is not an rviz related issue. 
This question should be better asked at https://answers.ros.org. Please, post real issues and bug reports here.
