### ISSUE TITLE
Path display with 'Pose Style' crashes on display toggle or global frame id switch

### ISSUE THREAD

**Issue by reinzor** [ros-visualization/rviz#1583]
![vokoscreen-2021-01-27_10-58-26](https://user-images.githubusercontent.com/4176023/105974862-9ec0f380-608e-11eb-8c99-727f40685c9c.gif)

- Unzip file: [path_pose_style_crash.zip](https://github.com/ros-visualization/rviz/files/5879209/path_pose_style_crash.zip)
- `roslaunch test.launch`
- Toggle the `path` display
- RVIZ crashes

### Your environment
* OS Version: e.g. Ubuntu 20.04
* ROS Distro: Noetic
* RViz, Qt, OGRE, OpenGl version as printed by rviz:

```
[ INFO][${node}][1611740173.157791220]: rviz version 1.14.4
[ INFO][${node}][1611740173.157864077]: compiled against Qt version 5.12.8
[ INFO][${node}][1611740173.157879165]: compiled against OGRE version 1.9.0 (Ghadamon)
[ INFO][/rviz_1611740173157956456][1611740173.164987165]: Forcing OpenGl version 0.
[ INFO][/rviz_1611740173157956456][1611740173.861507562]: Stereo is NOT SUPPORTED
[ INFO][/rviz_1611740173157956456][1611740173.861557934]: OpenGl version: 4.6 (GLSL 4.6).
```

**Comment by rhaschke** [comment]
Thanks for pointing this out. Looks like I introduced this bug when cleaning up unsigned/signed warnings a year ago in a22c731386b260cb56293cc205b191d88d7e9250. 
I pushed a fix: 5041755b436d94a7c39ec59cde70d7e449b7f1c3.
