### ISSUE TITLE
material color not showing up in RVIZ2

### ISSUE THREAD

**Issue by OldETC** [ros-visualization/rviz#1590]
Running urdf_tutorial material colors not showing up.
system: Toshiba Satellite 3.6 GiB AMD Athlon iip320 dual-core processor x 2 with AMD Rs880 graphics 
OS: ubuntu 20.04 LTS 64 bit Gnome 3.36.8  running x11 updated as of 2/16/2021
ROS foxy  running RVIZ2
program edited and running according to the tutorial.
each link shows a material like this:
    <material name="gray">
      <color rgba=".2 .2 .2 1" />
    </material>
where name and rgba changes for the different colors.
The robot model shows in white only.
The robot model has to be hand loaded by using the add button in RVIZ
The odom selection of fixed frame must be hand selected to get a display at all.
The TF buttons all seem to work OK.
help->About shows: This is RViz version Alpha (ROS2.0).
                                 Compiled against Qt version 5.12.8.
                                 Compiled against ORGE version 1.12.1 (Rhagorthua)
![image](https://user-images.githubusercontent.com/6307889/108416841-1d1f3a00-71e4-11eb-8094-f3436e4a5aae.png)
I have been struggling with this and other issues for about 2 months to continue my robot development.  I have the physical robot built, but I need this to work all the way so I can proceed. I also figured out that Gazebo was not being fully loaded when the ubuntu package was installed from their menu.  I hand installed it and some other utilities to get it to work this far.  The examples really don't help as much as I need to get this going.  It took tracking down lots of bits via google and duckduckgo.  But I am persistent, and look forward to seeing my robot walking soon.
Thanks for your consideration.

**Comment by rhaschke** [comment]
rviz2 has its own repo: https://github.com/ros2/rviz. Please report your issue over there.
