### ISSUE TITLE
NewObjectDialog* dialog not delete cause memory leak

### ISSUE THREAD

**Issue by tsukione** [ros-visualization/rviz#1601]
I found the 'dialog' is not deleted in visualization_frame
https://github.com/ros-visualization/rviz/blob/7383000e722d581dc8657f2bf6016fca88c4aee0/src/rviz/visualization_frame.cpp#L660-L669

but 'dialog' is appropriate deleted in displays_panel
https://github.com/ros-visualization/rviz/blob/7383000e722d581dc8657f2bf6016fca88c4aee0/src/rviz/displays_panel.cpp#L112-L127

**Comment by rhaschke** [comment]
Thanks for reporting. I filed #1602 to fix this.

**Comment by rhaschke** [comment]
Fixed via #1602.
