### ISSUE TITLE
ColorEditor cursor will jump to end when input text

### ISSUE THREAD

**Issue by tsukione** [ros-visualization/rviz#1607]
I try to input color value in ColorEditor, after any number input, the cursor will jump to end, see the gif.
![cursor_jump](https://user-images.githubusercontent.com/81400392/113654405-4f202900-96ca-11eb-84d7-e30bd38db18a.gif)

I found that cause by the model_->emitDataChanged(this);
https://github.com/ros-visualization/rviz/blob/ba536b2d5baae4be167f9741a3f5bcb05d129af6/src/rviz/properties/color_property.cpp#L60-L61

after a valid value is input, the dataChanged signal will call a setText() of QLineEdit. That make the cursor jump to end.

So, could the model_->emitDataChanged(this); be delete in ColorProperty? 
Now, I found this issue only in colorEditor.

### Environment
* OS Version: Ubuntu 18.04
* ROS Distro: Melodic
* RViz, Qt, OGRE, OpenGl version as printed by rviz:
```
[ INFO] [1617528442.570476806]: rviz version 1.13.16
[ INFO] [1617528442.570531904]: compiled against Qt version 5.9.5
[ INFO] [1617528442.570563003]: compiled against OGRE version 1.9.0 (Ghadamon)
[ INFO] [1617528442.574762879]: Forcing OpenGl version 0.
[ INFO] [1617528442.680312957]: Stereo is NOT SUPPORTED
[ INFO] [1617528442.680650647]: OpenGL device: llvmpipe (LLVM 10.0.0, 256 bits)
[ INFO] [1617528442.680780743]: OpenGl version: 3.1 (GLSL 1.4).
```

**Comment by rhaschke** [comment]
I can confirm this very annoying issue. However, just removing the call to `PropertyTreeModel::emitDataChanged` isn't the correct solution: Doing so, the data model (and thus rviz) don't notice changes anymore (e.g. for saving). #1609 proposes an alternative approach. @tsukione, please review.
