### ISSUE TITLE
RVIZ may crash when I scroll mouse in 3D view area

### ISSUE THREAD

**Issue by solookin** [ros-visualization/rviz#1613]
Hello, I meet a rviz crash.

when I scroll mouse in 3D view area and let the view scale very very small or very very big , the rivz will crash.

step 1: place a Plant Flat in 3D view area and set view type "TopDownOrtho".

![step1](https://user-images.githubusercontent.com/2277581/114263460-21174d80-9a18-11eb-89dc-f9cd35582870.jpg)

step 2: scroll my mouse in 3D view area, when the view scale is very very  big or very very small, rviz will crash.
![step2](https://user-images.githubusercontent.com/2277581/114263511-80755d80-9a18-11eb-88b8-7b8cf75f4755.jpg)

when crash, i can see crash log in terminal.

![step3](https://user-images.githubusercontent.com/2277581/114263536-aa2e8480-9a18-11eb-8981-15c6c241275b.jpg)

I guess should set min value range and max value range  of view_controller::ner_clip_property_    in any view controller ?

Your environment
  OS Version: Ubuntu 18.04
  ROS Distro: Melodic
  RViz, Qt, OGRE, OpenGl version as printed by rviz:

**Comment by rhaschke** [comment]
I'am afraid there is no generic min/max value for the scale. People might use very different scene scales as well...

**Comment by solookin** [comment]
> I'am afraid there is no generic min/max value for the scale. People might use very different scene scales as well...

OK. thanks.

**Comment by solookin** [comment]
Although people might use very different scene scales, but we can do something to avoid Rviz crashes ?

I edit the code in src/rviz/default_plugin/view_controllers/fixed_orientation_ortho_view_controller.cpp, it may work.


```
void FixedOrientationOrthoViewController::updateCamera()
{
  orientCamera();

  float width = camera_->getViewport()->getActualWidth();
  float height = camera_->getViewport()->getActualHeight();

  float scale = scale_property_->getFloat();
  Ogre::Matrix4 proj;
  
  // start
  // keep scale always valid to avoid rviz crashes #1613
  if (std::abs(width / scale / 2) == INFINITY || std::abs(height / scale / 2) == INFINITY) {
    scale_property_->setValue(last_valid_scale_);
    return;
  }
  if (std::abs(width / scale / 2) < 0.000001 || std::abs(height / scale / 2) < 0.000001) {
    scale_property_->setValue(last_valid_scale_);
    return;
  }
  last_valid_scale_ = scale;
  
  // end
  
  
  buildScaledOrthoMatrix( proj, -width / scale / 2, width / scale / 2, -height / scale / 2, height / scale / 2,
                          camera_->getNearClipDistance(), camera_->getFarClipDistance() );
  camera_->setCustomProjectionMatrix(true, proj);

  // For Z, we use half of the far-clip distance set in
  // selection_context.cpp, so that the shader program which computes
  // depth can see equal distances above and below the Z=0 plane.
  camera_->setPosition( x_property_->getFloat(), y_property_->getFloat(), 500 );
}
```

**Comment by rhaschke** [comment]
Please file a PR with your proposed changes. Here, I cannot immediately see what you actually propose to change.
