### ISSUE TITLE
The description on the Displays Panel will not refresh when the content of the selected property has changed

### ISSUE THREAD

**Issue by sunzbllbz** [ros-visualization/rviz#1614]
When the content of a selected property in a display has changed, the discription on the Displays Panel will not refresh automatically. For example, I choose the Image property in the Status of a Image plugin, which is updating the number of received Image message, but the number of received Image message in the Description area of the Displays Panel remain unchanged. That make me quiet puzzle.
![image](https://user-images.githubusercontent.com/81728978/114268460-cb509e80-9a33-11eb-8aaf-56b5567e751d.png)
After read the source code, I found that the description only changed when the selection had changed.  The change of the description is actived by void PropertyTreeWidget::currentChanged, which will only work when the selected item has been changed. 
To make the description update in real time, the current selected property can be recorded as a member of the rviz::PropertyTreeWidget, and connect the signal function - rviz::Property::changed to a new slot function - rviz::PropertyTreeWidget::currentSelectedPropertyChanged. When the selected property has changed, rviz::PropertyTreeWidget::currentSelectedPropertyChanged will be called and emit a signal to change the description. The patch to achieve this function is as below.
```
diff -ruN rviz-melodic-devel/src/rviz/properties/property_tree_widget.cpp rviz-melodic-devel-modified/src/rviz/properties/property_tree_widget.cpp
--- rviz-melodic-devel/src/rviz/properties/property_tree_widget.cpp	2021-03-26 03:27:15.000000000 +0800
+++ rviz-melodic-devel-modified/src/rviz/properties/property_tree_widget.cpp	2021-04-10 19:19:58.928264500 +0800
@@ -83,6 +83,19 @@
 {
   QTreeView::currentChanged(new_current_index, previous_current_index);
   Q_EMIT currentPropertyChanged(static_cast<const Property*>(new_current_index.internalPointer()));
+  if (currSelectedProperty != nullptr) {
+      disconnect(currSelectedProperty, SIGNAL(changed()), this, SLOT(currentSelectedPropertyChanged()));
+  }
+  currSelectedProperty = static_cast<const Property*>(new_current_index.internalPointer());
+  if (currSelectedProperty == nullptr) {
+      return;
+  }
+  connect(currSelectedProperty, SIGNAL(changed()), this, SLOT(currentSelectedPropertyChanged()));
+}
+
+void PropertyTreeWidget::currentSelectedPropertyChanged()
+{
+  Q_EMIT currentPropertyChanged(currSelectedProperty);
 }
 
 void PropertyTreeWidget::selectionChanged(const QItemSelection& selected,
diff -ruN rviz-melodic-devel/src/rviz/properties/property_tree_widget.h rviz-melodic-devel-modified/src/rviz/properties/property_tree_widget.h
--- rviz-melodic-devel/src/rviz/properties/property_tree_widget.h	2021-03-26 03:27:15.000000000 +0800
+++ rviz-melodic-devel-modified/src/rviz/properties/property_tree_widget.h	2021-04-10 19:14:57.976264500 +0800
@@ -110,6 +110,8 @@
 protected Q_SLOTS:
   virtual void propertyHiddenChanged(const Property* property);
 
+  void currentSelectedPropertyChanged();
+
 Q_SIGNALS:
   void currentPropertyChanged(const Property* new_current_property);
   void selectionHasChanged();
@@ -124,6 +126,7 @@
                      const QModelIndex& parent_index,
                      const QString& prefix);
 
+  const Property *currSelectedProperty = nullptr;
   PropertyTreeModel* model_;
   SplitterHandle* splitter_handle_;
 };

```
Do you consider it as a problem or do you have better solution? Welcome to further discussion.

### Your environment
* OS Version: e.g. Ubuntu 18.04
* ROS Distro: Melodic
* RViz, Qt, OGRE, OpenGl version as printed by rviz:

```
 [ INFO] [1618111147.865419495]: rviz version 1.13.14
 [ INFO] [1618111147.865468815]: compiled against Qt version 5.9.5
 [ INFO] [1618111147.865478205]: compiled against OGRE version 1.9.0 (Ghadamon)
 [ INFO] [1618111147.871115755]: Forcing OpenGl version 0.
 [ INFO] [1618111148.186349535]: Stereo is NOT SUPPORTED
 [ INFO] [1618111148.186397092]: OpenGl version: 4.6 (GLSL 4.6).
```

**Comment by rhaschke** [comment]
Personally, I wouldn't update the description in a live fashion. Nobody else complained about this in the past and it adds just another update call, which will affect overall performance of rviz. We know that we need to look at the value field of the property instead...
However, if there are more people voting for your suggested change, it is highly welcome. However, your solution will change ABI by introducing a new class member! This will not be accepted.
