### ISSUE TITLE
RVIZ may crash when place a PlantFlag after click "Reset" button.

### ISSUE THREAD

**Issue by solookin** [ros-visualization/rviz#1618]
RVIZ may crash when place a FlatFlag after click "Reset" button.

step1: click "+"  and add PlantFlag

![step1](https://user-images.githubusercontent.com/2277581/114330014-57b5ab00-9b73-11eb-9c1b-041c5bf5c221.jpg)

step2: click "Reset" button on status bar.

![step2](https://user-images.githubusercontent.com/2277581/114330076-77e56a00-9b73-11eb-9c82-af7397263188.jpg)

step3: place a PlantFlag on 3D view area.  and then rviz will crash.  crash log show as below.
```
[ INFO] [1618175188.220977900]: rviz version 1.13.14
[ INFO] [1618175188.221048800]: compiled against Qt version 5.9.5
[ INFO] [1618175188.221061000]: compiled against OGRE version 1.9.0 (Ghadamon)
[ INFO] [1618175188.224373400]: Forcing OpenGl version 0.
[ INFO] [1618175188.336597100]: Stereo is NOT SUPPORTED
[ INFO] [1618175188.336697400]: OpenGl version: 3.1 (GLSL 1.4).
[ WARN] [1618175535.307499300]: OGRE EXCEPTION(6:FileNotFoundException): Cannot locate resource package://rviz_plugin_tutorials/media/flag.dae in resource group Autodetect or any other group. in ResourceGroupManager::openResource at /build/ogre-1.9-B6QkmW/ogre-1.9-1.9.0+dfsg1/OgreMain/src/OgreResourceGroupManager.cpp (line 756)
terminate called after throwing an instance of 'Ogre::FileNotFoundException'
  what():  OGRE EXCEPTION(6:FileNotFoundException): Cannot locate resource package://rviz_plugin_tutorials/media/flag.dae in resource group Autodetect or any other group. in ResourceGroupManager::openResource at /build/ogre-1.9-B6QkmW/ogre-1.9-1.9.0+dfsg1/OgreMain/src/OgreResourceGroupManager.cpp (line 756)
```

### Your environment
* OS Version: Ubuntu 18.04 and Ubuntu 16.04
* ROS Distro: Kinetic and Melodic
* RViz, Qt, OGRE, OpenGl version as printed by rviz:

**Comment by rhaschke** [comment]
Thanks for reporting. The issue was actually wrong API usage in source of `visualization_tutorials`.
PR filed: https://github.com/ros-visualization/visualization_tutorials/pull/67

**Comment by solookin** [comment]
thanks
