### ISSUE TITLE
Visualization of the 2D Pose Estimate or 2D Nav Goal tools with the help of a marker or something similar

### ISSUE THREAD

**Issue by andu215** [ros-visualization/rviz#1640]
Hello all,

When using the 2D Pose Estimate or 2D Nav Goal tool, is it possible to display the clicked point visually via a marker or similar? 
And that this marker also remains on the map, even when clicking on another point.

Thanks for your help in advance

### My environment
* OS Version: Ubuntu 18.04
* ROS Distro: Melodic
*This is RViz version 1.13.16 (melodic).
Compiled against Qt version 5.9.5.
Compiled against OGRE version 1.9.0 (Ghadamon).

**Comment by rhaschke** [comment]
I thought I already answered this: Of course you can publish any marker of your choice from your application to indicate that you reacted to the 2D nav goal. As this is highly application-specific, there is no generic solution for this available.
