### ISSUE TITLE
Passing state between tools in an Rviz plugin

### ISSUE THREAD

**Issue by aa-tom** [ros-visualization/rviz#1648]
Hi,

I'm looking to write an rviz plugin adding some tools for interacting with meshes, specifically selecting and publishing a subset of faces on a mesh. I'm quite new to rviz development so would much appreciate any advice on the cleanest way to implement this. At the moment I'm thinking of the following:

1. A "selection" tool allowing a specific mesh to be focused on
2. A "paint" tool allowing the user to click and drag to select faces **on the focused mesh** within some defined radius of the cursor
3. A new panel containing a "publish" button allowing the selected subset of faces to be published to a topic

In order to implement the above, the selection tool would need to maintain some state about the currently focused mesh, and the paint tool would need to be able to access this state to determine whether clicked faces should be selected based on whether they're part of the focused mesh.

Is passing state between tools easy to do in rviz? Is there a better approach?

**Comment by rhaschke** [comment]
It is already possible to select objects in rviz. Just use the selection tool. What kind of meshes do you think of? There are dozens of visual objects that are displayed using a mesh.
Exchanging info between different objects isn't easy. I suggest letting the panel also create the tool (and possibly vice versa).
In this fashion, you can ensure that they are both created and you can pass the other's pointer for access to any info.

**Comment by aa-tom** [comment]
Ah yeah the selection tool looks perfect for step 1.

The meshes would come in STL format and could be of arbitrary shape. The important part is that the faces should be able to be colored individually so we can render the selected faces in a different color. I think a TRIANGLE_LIST marker may be suitable for this, along with some code to load an STL and publish the appropriate visualization messages & keep track of selection state.

I'm a little hazy on the details of rviz, so I was wondering if you could explain the details of having the panel create the tool a bit more. Obviously I could instantiate an instance of the tool in the panel, but isn't rviz also doing this in the background when the plugin is loaded? Would having two instances of the tool cause any issues?

**Comment by rhaschke** [comment]
You are right: rviz doesn't limit the number of tool or panel instances of a particular type. However, keeping track of the created tools / panels of _your_ particular type(s), you can know whether or not to create the missing other piece. In the same fashion you can interlink them, i.e. based on your knowledge of what was already created. This is kind of working around the (intended) limitation that rviz objects cannot directly interact with each other.

If a tool / panel is instantiated, they will be saved into the config file and also restored from there. Again you should take care not to create them twice - if that's something you care about.

Regarding the meshes: Won't they interact with the rest of rviz? How do you distinguish _your_ marker from other markers?
If you just want to have a standalone program to handle your meshes, I suggest using librviz as part of your own main program! This gives you full control over loaded (or not loaded) plugins, tools, panels, etc.

**Comment by aa-tom** [comment]
I'm imagining the selected faces will be published to a topic which another component of the system will pick up and process. Rviz would just be the UI of our process in that regard. That being said, the mesh will be embedded in a larger scene consisting of a robot, cell, etc... which are already in rviz, so I think it'd make sense to combine all the visual elements there rather than having separate rviz apps for different parts.

I suppose the panel I create could hold a reference to the marker Display for the mesh in order to facilitate communication with the correct one. I'm still a little confused around the tool. My thinking goes something like:

1. The panel is added by the user. At this point it creates an instance of the tool
2. After loading a mesh, the user clicks on the tool. I think a second instance would be created at this point?
3. Somehow, the info about the mouse click from the tool needs to get to the panel so the selected faces can be updated (and then to the visual so the colour can be updated)

I'm struggling to see how holding a reference to a separate tool instance would help here. Wouldn't the instance created when the user selects the tool be entirely separate? Is there a way for a panel to fetch a reference to the currently selected tool?Alternatively, I'm wondering if it'd be simpler to have all of these parts communicate through topics

**Comment by rhaschke** [comment]
Selecting a tool doesn't _create_ a new instance of the tool, it just makes the existing tool instance the _current_ tool, processing all mouse + keyboard inputs. I think like this:
1. The panel is added by the user. At this point it creates an instance of the tool
2. User loads a mesh. Some reference of this mesh is passed to the tool, so the tool knows what to care about
3. If the user interacts with the mesh via the tool, changes are applied to the mesh and possibly communicated to the panel

**Comment by aa-tom** [comment]
Ahh okay, that makes sense to me. Think I'm in a good place to start implementing now. Should be able to take a look at the docs for specific questions around classes & functions available. Thanks for the help :smile:
