### ISSUE TITLE
The plugin for class 'jsk_rviz_plugin/BoundingBox' failed to load.

### ISSUE THREAD

**Issue by WiNet-Lab-IIT-Hyderabad** [ros-visualization/rviz#1669]
Describe your issue here and explain how to reproduce it.
In rviz jsk bounding boz isa not working.
### Your environment
* OS Version:  Ubuntu 18.04
* ROS Distro: Melodic
* RViz, Qt, OGRE, OpenGl version as printed by rviz:
    ```
    paste your console output here
    ```
bhaskar@bhaskar:~$ rviz
[ INFO] [1632309468.929576303]: rviz version 1.13.18
[ INFO] [1632309468.929616904]: compiled against Qt version 5.9.5
[ INFO] [1632309468.929627362]: compiled against OGRE version 1.9.0 (Ghadamon)
[ INFO] [1632309468.935375665]: Forcing OpenGl version 0.
[ INFO] [1632309469.498149342]: Stereo is NOT SUPPORTED
[ INFO] [1632309469.498202934]: OpenGL device: NVIDIA GeForce RTX 3090/PCIe/SSE2
[ INFO] [1632309469.498216452]: OpenGl version: 4.6 (GLSL 4.6).
[ERROR] [1632309477.418149497]: PluginlibFactory: The plugin for class 'jsk_rviz_plugin/BoundingBox' failed to load.  Error: Failed to load library /opt/ros/melodic/lib//libjsk_rviz_plugins.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = /opt/ros/melodic/lib/libjsk_recognition_utils.so: undefined symbol: _ZNK3pcl6search6SearchINS_8PointXYZEE7getNameB5cxx11Ev)

**Comment by rhaschke** [comment]
This is an issue with libjsk_rviz_plugins.so, not of rviz. 
Please report this issue over there: https://github.com/jsk-ros-pkg/jsk_visualization
