### ISSUE TITLE
RViz may crash when TF's childFrameId is " "

### ISSUE THREAD

**Issue by qinshichao** [ros-visualization/rviz#1699]
When the childframeid of TF is ' ' and subscribed, RViz will crash.
![bug](https://user-images.githubusercontent.com/24313254/151276459-ea17a0ef-0c29-48a0-9bf7-a0f2c4e72a19.png)

When the childframeid of TF is '\a'  or '\e' or other strings starting with' \ ',Abnormal display of RViz.
![Abnormal display](https://user-images.githubusercontent.com/24313254/151276544-5c618bad-8a26-491f-b574-9fa60ec70515.png)

### Your environment
* OS Version: e.g. Ubuntu 18.04
* ROS Distro: [Melodic]
* RViz, Qt, OGRE, OpenGl version as printed by rviz:

![bug](https://user-images.githubusercontent.com/24313254/151276494-9cb04804-cc3c-4cad-b646-0295b0a8f781.png)

**Comment by rhaschke** [comment]
I cannot confirm these issues:
TF already rejects/ignores an empty child transform with the following error message on console:
`[ERROR] ros.rosconsole_bridge.TF_NO_CHILD_FRAME_ID: Ignoring transform from authority "unknown_publisher" because child_frame_id not set`

When sending a child frame with a non-printable control character in its name (e.g. `\a`), what exactly do you expect to happen?

**Comment by qinshichao** [comment]
> I cannot confirm these issues: TF already rejects/ignores an empty child transform with the following error message on console: `[ERROR] ros.rosconsole_bridge.TF_NO_CHILD_FRAME_ID: Ignoring transform from authority "unknown_publisher" because child_frame_id not set`
> 
> When sending a child frame with a non-printable control character in its name (e.g. `\a`), what exactly do you expect to happen?

It's not empty, it's a space.
When sending a child frame with a non-printable control character in its name (e.g. \a), I expect it to remain '\ a' without escape.

**Comment by qinshichao** [comment]
> To have a frame name like `\a` you obviously need to escape the backslash like so: `"\\a"
Can string escape be prevented in code?

**Comment by rhaschke** [comment]
> To have a frame name like `\a` you obviously need to escape the backslash like so: `"\a"

> > Can string escape be prevented in code?

No. That's about interpretation of chars in your programming language:
-  `\a` is interpreted as a control character
- `\\a` is interpreted as backslash + letter a

**Comment by rhaschke** [comment]
crash fixed via #1700.
