### ISSUE TITLE
Mesh with normal have no light in latest release 1.14.13 (regression since 1.14.11)

### ISSUE THREAD

**Issue by xbroquer** [ros-visualization/rviz#1702]
Hello @rhaschke ,

Affect version : ROS Noetic , ubuntu 20.04
RViz 1.14.13 installed using ubuntu apt upgrade on Jan 27th 2022

In my ROS setup I display some meshes generated using blender. After rviz upgrade the RVIZ 3D scene  seems to have no light.

I cloned rviz in my catkin workspace and checked out tag 1.14.11: no issue

I compared the changes between 1.14.11 and HEAD of noetic-devel, I found some changes in mesh_loader.
After investigation I found that you removed the transformation of normals.

By re-applying the transformation on normals , the mesh is well rendered.

My local revert:
![2022-01-27_21h22_27](https://user-images.githubusercontent.com/3864052/151437715-058ab919-f109-4c3c-8a2d-0056a4b947c3.png)

with lastest release:

![2022-01-27_21h36_05](https://user-images.githubusercontent.com/3864052/151439835-305e7ad2-5cd4-4199-b3b4-a97f6852032b.png)

With the patch:

![2022-01-27_21h35_04](https://user-images.githubusercontent.com/3864052/151439828-d186001d-a04c-426a-9fa2-2757ecf7924c.png)

Here a mesh:
[truck.zip](https://github.com/ros-visualization/rviz/files/7957410/truck.zip)

**Comment by rhaschke** [comment]
Could you please provide an example mesh file exhibiting this behavior?

**Comment by rhaschke** [comment]
I believe that the complicated transform is not needed, because it just rescales the normals, which is subsequently undone by normalizing the vectors. However, it looks like I removed the transform completely. I think #1703 should already solve the issue. Could you please verify? Please, provide an example mesh in any case. Thanks.

**Comment by xbroquer** [comment]
Thanks for your quick reply, I am not allowed to attach the small car, but I attached a truck, I am testing #1703 and come back to you asap

**Comment by xbroquer** [comment]
![2022-01-28_10h45_51](https://user-images.githubusercontent.com/3864052/151526524-41e96bfb-8c69-4da6-8190-0c8e83b465d8.png)

![2022-01-28_10h37_17](https://user-images.githubusercontent.com/3864052/151526537-3e3d279a-e5a1-4372-9303-8589921b4cb1.png)

**Comment by rhaschke** [comment]
I couldn't find the truck mesh file - there was no attachment. But from your pictures, I conclude that my simpler fix resolves the issue for you?

**Comment by xbroquer** [comment]
no, in my previous comment , the first screenshot is with the "simple" fix. 
I will add the mesh in my https://github.com/xbroquer/rviz_collada_marker this afternoon along with launch + rviz conf file

**Comment by xbroquer** [comment]
Can you please try: roslaunch rviz_collada_marker test_truck.launch from https://github.com/xbroquer/rviz_collada_marker

**Comment by xbroquer** [comment]
Using #1703:
![2022-01-28_13h42_14](https://user-images.githubusercontent.com/3864052/151550314-11dd5c9d-1721-4a49-bc1d-f6e434c401a3.png)
It's not cpompletely dark when moving the rviz camera:
![2022-01-28_13h42_33](https://user-images.githubusercontent.com/3864052/151550331-aa5dd31d-bda3-441c-a055-d11e7d4fb328.png)

Here using  https://github.com/xbroquer/rviz/commit/3ac6cf41eb3ccd2cd769e775557f44fe6e177196
![2022-01-28_13h44_21](https://user-images.githubusercontent.com/3864052/151550343-041ac9c3-aa4f-4e06-9f54-21037d469643.png)

**Comment by rhaschke** [comment]
I fixed the issue in #1703. Thanks for providing the mesh file. This helped to debug this issue.

**Comment by xbroquer** [comment]
Thanks! Do you know when I should expect this fix released and available on deb repo for Noetic ?

**Comment by rhaschke** [comment]
I will prepare a release within next week latest.
However, both Melodic and Noetic just recently had a sync: https://discourse.ros.org/c/release/16. Thus, it will take a month or so until the next release will be available. Consider using the debian packages from the [ROS `testing` repo](http://wiki.ros.org/TestingRepository) meanwhile.

**Comment by rhaschke** [comment]
Fixed via #1703
