### ISSUE TITLE
Undefined Symbol

### ISSUE THREAD

**Issue by atyshka** [ros-visualization/rviz#1705]
Using a fresh installation of ROS Noetic on ubuntu 20.04, RViz does not seem to load correctly from the parameter file. When I launch rviz, I see the following blank layout:
![Screenshot from 2022-01-31 11-59-18](https://user-images.githubusercontent.com/19317207/151838354-6277a255-5167-428b-8339-f6dca92e1dbe.png)
Rviz is clearly not loading the default config correctly. So I attempt to open it manually and rviz crashed with the following error:
`rviz: symbol lookup error: /opt/ros/noetic/lib/librviz.so: undefined symbol: _ZN4YAML7Emitter5WriteERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
`
Something seems to be wrong with the YAML library linked with RViz? I uninstalled Rviz with an apt remove --purge and reinstalled it. I also ran a full system upgrade so that should not be the issue. I am at a loss as to what could be causing this and may end up having to reinstall ubuntu

### Your environment
* OS Version: e.g. Ubuntu 20.04
* ROS Distro: Noetic
* RViz, Qt, OGRE, OpenGl version as printed by rviz:
    ```
[ INFO] [1643648347.592786867]: rviz version 1.14.13
[ INFO] [1643648347.592831596]: compiled against Qt version 5.12.8
[ INFO] [1643648347.592837393]: compiled against OGRE version 1.9.0 (Ghadamon)
[ INFO] [1643648347.597508899]: Forcing OpenGl version 0.
    ```
* If source build, which git commit? NA
* System locale, i.e. the output of `echo "$LANG $LC_NUMERIC"`: en_US.UTF-8

**Comment by atyshka** [comment]
Found the issue with another installed package taking precedence over libyaml-cpp

**Comment by smihael** [comment]
@atyshka I am facing the same issue. What were the steps for you to resolve it?

**Comment by smihael** [comment]
I was facing the same problem. I checked LD_LIBRARY_PATH environment variable, to find out the candidate packages that might interfere with the mentioned library.  In my case, I needed to disable /etc/profile.d/nuitrack_env.sh

**Comment by souljaboy764** [comment]
I saw found that the is as @atyshka mentioned, the Nuitrack debian package ships it's own version of libyaml-cpp which gets linked to the rviz libraries/binaries instead of the one from the system. I managed to get it working by copying the library installed at the system level to the place where the one from nuitrack is installed.

**Comment by chnsssmnn** [comment]
Hi, 
I'm facing the same issue. @smihael Could you tell me where to find the the library installed at system level and where the one from nuitrack is installed?

**Comment by rhaschke** [comment]
The system lib is installed in /usr/lib/x86_64-linux-gnu/libyaml-cpp.so.0.6.
Probably, you just need to adapt your `LD_LIBRARY_PATH` environment variable. 
Copying different lib versions around is not recommended as mixing lib versions will break one or the other app.

**Comment by chnsssmnn** [comment]
@rhaschke This is the output of echo $LD_LIBRARY_PATH 
![image](https://github.com/ros-visualization/rviz/assets/37604299/651ab9c5-35d1-438a-aab0-b8d53596c750)

But rviz still has the error mentioned in the initial post

**Comment by rhaschke** [comment]
Check with `ldd /opt/ros/noetic/lib/rviz/rviz` which `libyaml-cpp` is actually used and where it comes from.

**Comment by chnsssmnn** [comment]
It is using the one from nuitrack: 
![image](https://github.com/ros-visualization/rviz/assets/37604299/b826b013-b9cb-4948-8fc8-0815270e8228)

**Comment by rhaschke** [comment]
/usr/local/lib takes precedence over /usr/lib. My suggestion is to create a symlink to /usr/lib/x86_64-linux-gnu/libyaml-cpp.so in /opt/ros/noetic/lib
