### ISSUE TITLE
rviz python qt bind not found, not cmake

### ISSUE THREAD

**Issue by kennydedavion** [ros-visualization/rviz#1712]
good day. I cloned rpi3b with raspbian buster ros kinetic due to the spotmicro package. but now after cloning the beetroot speaks catkin make that he misses qt bind:

Linux raspberrypi 5.10.63-v7+ #1496 SMP Wed Dec 1 15:58:11 GMT 2021 armv7l GNU/Linux
ROS Distro: Kinetic 
 printed by rviz:
    ```
   ==> Processing catkin package: 'rviz'
==> Building with env: '/home/pi/ros_catkin_ws/install_isolated/env.sh'
==> cmake /home/pi/ros_catkin_ws/src/rviz -DCATKIN_DEVEL_PREFIX=/home/pi/ros_catkin_ws/devel_isolated/rviz -DCMAKE_INSTALL_PREFIX=/home/pi/ros_catkin_ws/install_isolated -G Unix Makefiles in '/home/pi/ros_catkin_ws/build_isolated/rviz'
-- OGRE_INCLUDE_DIRS=/usr/include/OGRE/Overlay;/usr/include/OGRE
-- OGRE_LIBRARIES=/usr/lib/arm-linux-gnueabihf/libOgreOverlay.so;/usr/lib/arm-linux-gnueabihf/libOgreMain.so;/usr/lib/arm-linux-gnueabihf/libpthread.so
-- OGRE_PLUGIN_DIR=/usr/lib/arm-linux-gnueabihf/OGRE-1.9.0
-- Using CATKIN_DEVEL_PREFIX: /home/pi/ros_catkin_ws/devel_isolated/rviz
-- Using CMAKE_PREFIX_PATH: /home/pi/ros_catkin_ws/install_isolated
-- This workspace overlays: /home/pi/ros_catkin_ws/install_isolated
-- Found PythonInterp: /usr/bin/python2 (found suitable version "2.7.16", minimum required is "2") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python2
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/pi/ros_catkin_ws/build_isolated/rviz/test_results
-- Forcing gtest/gmock from source, though one was otherwise available.
-- Found gtest sources under '/usr/src/googletest': gtests will be built
-- Found gmock sources under '/usr/src/googletest': gmock will be built
-- Found PythonInterp: /usr/bin/python2 (found version "2.7.16") 
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.7.29
-- BUILD_SHARED_LIBS is on
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- Could NOT find python_qt_binding (missing: python_qt_binding_DIR)
-- Could not find the required component 'python_qt_binding'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "python_qt_binding"
  with any of the following names:

    python_qt_bindingConfig.cmake
    python_qt_binding-config.cmake

  Add the installation prefix of "python_qt_binding" to CMAKE_PREFIX_PATH or
  set "python_qt_binding_DIR" to a directory containing one of the above
  files.  If "python_qt_binding" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:117 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/pi/ros_catkin_ws/build_isolated/rviz/CMakeFiles/CMakeOutput.log".
See also "/home/pi/ros_catkin_ws/build_isolated/rviz/CMakeFiles/CMakeError.log".
<== Failed to process package 'rviz': 
  Command '['/home/pi/ros_catkin_ws/install_isolated/env.sh', 'cmake', '/home/pi/ros_catkin_ws/src/rviz', '-DCATKIN_DEVEL_PREFIX=/home/pi/ros_catkin_ws/devel_isolated/rviz', '-DCMAKE_INSTALL_PREFIX=/home/pi/ros_catkin_ws/install_isolated', '-G', 'Unix Makefiles']' returned non-zero exit status 1


    ```
instructions I used: wiki.ros.org install ROSberryPiInstalling ROS Kinetic on the Raspberry Pi
pip3 qt is:  python-pyqt5 (5.11.3+dfsg-1+rpi1+b3) install

when i use cloning python_qt from rosvisualization / python_qt_binding github save and run the compilation again, the python_qt_binding package will show that it is unknown for cmake and when creating the build folder inside repa python_qt_binding kinetic version, the system is missing so dale a. cm I am not a developer or an expert on Linux systems. after reading that rosdep installs all the dependencies, and its launch, which only announces that it can not find the dependencies, I am already completely clueless. motam is missing addiction in the circle, it cannot be installed because the display install ros-kinetic ...., rosdep install ros-desktop ...... does not work. the package is either not found or is in a faulty condition.
to say that I will burn a new rose again and perform the installation again only leads to the same unsolvable or other problem, for which there is no link or mention, because either tutorial nano or melody or not used is used in the tutorials. rpi3. how to solve this so that the installation of the workspace is ok and I don't have to bother with a million versions and thousands of varieties and a ton of other versions that are not for me? REALLY ONE WHAT'S ALL ABOUT is having this repo functional: https: //github.com/mike4192/spotMicro on my rpi3. ros bleeeee

**Comment by rhaschke** [comment]
This is not an issue related to this source repository. Please contact the distro maintainer for Rasberry / ARM.
By the way, why do you try to install ROS Kinetic (EOL) instead of more recent [ROS Melodic](http://wiki.ros.org/ROSberryPi/Installing%20ROS%20Melodic%20on%20the%20Raspberry%20Pi)?
