### ISSUE TITLE
Rviz terminal print the error problems of QObject::connect

### ISSUE THREAD

**Issue by qisongH** [ros-visualization/rviz#1723]
![image](https://user-images.githubusercontent.com/74614539/157648374-d7985c30-0225-4cd2-ae16-dc05a5a7915d.png)

I use the PointClound2 plug-in to subscribe point cloud data. The data is displayed normally, **but the terminal prints the following error information:**
![image](https://user-images.githubusercontent.com/74614539/157648321-ef82c786-e60f-4d64-80ea-f0c5fa4c30fb.png)

### Your environment
* OS Version: e.g. Ubuntu 18.04
* ROS Distro: Melodic
* RViz, Qt, OGRE, OpenGl version as printed by rviz:
    ```
    [ INFO] [1646653665.369882000]: rviz version 1.13.23
    [ INFO] [1646653665.369933300]: compiled against Qt version 5.9.5
    [ INFO] [1646653665.369944800]: compiled against OGRE version 1.9.0 (Ghadamon)
    [ INFO] [1646653665.373622300]: Forcing OpenGl version 0.
    [ INFO] [1646653665.491788300]: Stereo is NOT SUPPORTED
    [ INFO] [1646653665.492296300]: OpenGL device: llvmpipe (LLVM 10.0.0, 256 bits)
    [ INFO] [1646653665.492382900]: OpenGl version: 3.1 (GLSL 1.4).
    ```

**Comment by rhaschke** [comment]
I wasn't able to reproduce this issue with a PC2 display. Please provide more detailed instructions to reproduce the problem.
