### ISSUE TITLE
No transform from [front_caster_link] to [base_link]

### ISSUE THREAD

**Issue by magicjia2** [ros-visualization/rviz#1735]
Describe your issue here and explain how to reproduce it.

### Your environment
* OS Version: e.g. Ubuntu 18.04
* ROS Distro: [Kinetic | Melodic | Noetic]
* RViz, Qt, OGRE, OpenGl version as printed by rviz:
    ```
    paste your console output here
    ```
* If source build, which git commit?
* System locale, i.e. the output of `echo "$LANG $LC_NUMERIC"`:
  Before reporting a rendering issue, try running RViz with `LANG=C rviz`!

**Comment by rhaschke** [comment]
Closing due to missing issue description. Check your TF transform tree! The error description is very clear: there is no TF transform available from `front_caster_link` to `base_link`. Is there a (robot_transform_)publisher publishing those transforms?
