### ISSUE TITLE
Associated widget which is docked creating a tabbed panels gets disabled if tab is not visible

### ISSUE THREAD

**Issue by Levi-Armstrong** [ros-visualization/rviz#1738]
Currently if I dock my panel on top of another panel creating tabbed panels and then you switched tab it disables the display. Is there a way to disable this functionality?

**Comment by Levi-Armstrong** [comment]
I believe this a related [issue](https://github.com/ros-visualization/rviz/issues/940) but the issue shows resolved but this still appears to be happening on noetic version.

**Comment by Levi-Armstrong** [comment]
Tab Selected
![image](https://user-images.githubusercontent.com/9803128/164224093-6088275f-2004-43e7-94ee-979a9a046d74.png)

Tab Unselected
![image](https://user-images.githubusercontent.com/9803128/164224218-a7bdbe20-514d-418d-9bb9-3ff3f3a786e8.png)

**Comment by Levi-Armstrong** [comment]
Then I can enable the display from the tree and the scene is visible and the tab is not which is the behavior expected.
![image](https://user-images.githubusercontent.com/9803128/164227352-bbd2e285-2052-4bbd-8691-f61cdbed65de.png)

**Comment by Levi-Armstrong** [comment]
A current work around is to add the following connection enabling the display on any visibility change to the panel.

``` c++
connect(getAssociatedWidgetPanel(), SIGNAL( visibilityChanged( bool ) ), this, SLOT( onAssociatedPanelVisibilityChange( bool ) ));
```

``` c++
void WorkbenchDisplay::onAssociatedPanelVisibilityChange(bool /*visible*/)
{
  setEnabled(true);
}
```

**Comment by Levi-Armstrong** [comment]
Well actually that does not work because now the display cannot be disabled.

**Comment by Levi-Armstrong** [comment]
Finally was able to create a work around.

I first had to disconnect the following signal.

``` c++
disconnect(getAssociatedWidgetPanel(), SIGNAL( visibilityChanged(bool) ), this, SLOT( associatedPanelVisibilityChange(bool) ));
```

Then override the `onEnableChanged` with the following
``` c++
void WorkbenchDisplay::onEnableChanged()
{
  QApplication::setOverrideCursor(QCursor(Qt::WaitCursor));
  queueRender();
  /* We get here, by two different routes:
   * - First, we might have disabled the display.
   *   In this case we want to close/hide the associated widget.
   *   But there is an exception: tabbed DockWidgets shouldn't be hidden, because then we would loose the
   * tab.
   * - Second, the corresponding widget changed visibility and we got here via
   * associatedPanelVisibilityChange().
   *   In this case, it's usually counterproductive to show/hide the widget here.
   *   Typical cases are: main window was minimized/unminimized, tab was switched.
   */
  if (isEnabled())
  {
    scene_node_->setVisible(true);

    if (getAssociatedWidgetPanel() != nullptr)
    {
      getAssociatedWidgetPanel()->show();
      getAssociatedWidgetPanel()->setEnabled(true);
    }
    else if (getAssociatedWidget() != nullptr)
    {
      getAssociatedWidget()->show();
      getAssociatedWidgetPanel()->setEnabled(true);
    }

    if (isEnabled()) // status might have changed, e.g. if show() failed
      onEnable();
  }
  else
  {
    onDisable();

    if (getAssociatedWidgetPanel() != nullptr)
      getAssociatedWidgetPanel()->setDisabled(true);
    else if (getAssociatedWidget())
      getAssociatedWidget()->setDisabled(true);

    scene_node_->setVisible(false);
  }
  QApplication::restoreOverrideCursor();
}
```
This just disables the widget opposed to hiding and showing.

**Comment by rhaschke** [comment]
There is a simpler solution: #1739.

**Comment by Levi-Armstrong** [comment]
> There is a simpler solution: #1739.

Thanks for the fix.

**Comment by Levi-Armstrong** [comment]
Sure, it is under a lot of development at the moment. [tesseract_gui](https://github.com/tesseract-robotics/tesseract_gui)
