### ISSUE TITLE
[feature request] Better Qt5 support for Slots

### ISSUE THREAD

**Issue by kunaltyagi** [ros-visualization/rviz#1742]
Currently, all properties have a ctor which takes in slots as `char*`. However, since Qt5, there's an option to take slot as a member function or even a functor.

Links
* [Qt4 details](https://woboq.com/blog/how-qt-signals-slots-work.html)
* [Qt5 details](https://woboq.com/blog/how-qt-signals-slots-work-part2-qt5.html)

Would a PR touching multiple property and derived class ctor be entertained?

**Comment by rhaschke** [comment]
A corresponding PR supporting the new scheme is highly welcome. The old scheme should be still supported of course.
I'm looking forward to this contribution :smile:
