### ISSUE TITLE
RVIZ initialization failed in win10,  Orbit cant be loaded

### ISSUE THREAD

**Issue by GavinGaoYan** [ros-visualization/rviz#1755]
### Your environment
* OS Version: win10
* ROS Distro: Melodic

![J8{HHQGF@LZMQU4_QIJRBBG](https://user-images.githubusercontent.com/29242454/178932784-8b6b9fa6-5bb0-4dd9-8f6a-12193ddef7e8.png)
![image](https://user-images.githubusercontent.com/29242454/178933113-5c20468e-8e59-4422-8851-df9748bb7f53.png)

dll problem？

**Comment by rhaschke** [comment]
We don't officially support Windows. So, you are on your own. My guess is that `rviz_default_plugin.dll` (comprising all plugins) is not in your PATH.
