### ISSUE TITLE
How to save image in RVIZ with high resolution? 

### ISSUE THREAD

**Issue by QUIlToT** [ros-visualization/rviz#1768]
It seems that images can only be saved this way: `File->Save image`

But the format and resolution of the image cannot be adjusted as expected. 

Is there any other way to save high-resolution images or other formats like `.svg`?

**Comment by rhaschke** [comment]
No, this is not supported (and not planned). If you like to contribute such a feature, [this post](https://wiki.ogre3d.org/Render+to+SVG) might be a good starting point.
