### ISSUE TITLE
rviz saves the config and then opens it, the previously added Panel loading does not meet expectations

### ISSUE THREAD

**Issue by ysl-design** [ros-visualization/rviz#1769]
Describe your issue here and explain how to reproduce it.

I added 3 Camera plugins and 1 Image plugin to the rviz, then added 2 Views panels, 
![image](https://user-images.githubusercontent.com/67178569/192541479-db6bf5dd-37e9-44d6-8481-4d1fd0aa5b61.png)
and then selected “Save” when closing rviz to save the added plugins. 
![image](https://user-images.githubusercontent.com/67178569/192524440-142f55e1-322a-4edb-a775-b55ba644927a.png)
Start rviz again, the two Views Panels are expected to be in the original lower left corner, but the actual situation is that they are gone, and the Views check box in the Panels drop-down menu is unchecked. Other Panels have the same phenomenon.  I would like to ask what is the reason why Panels cannot save the location.
![image](https://user-images.githubusercontent.com/67178569/192524891-59055e3a-1a48-4277-904f-fa6ea90b6aed.png)

### Your environment
* OS Version: Ubuntu 20.04
* ROS Distro: Noetic
* RViz, Qt, OGRE, OpenGl version as printed by rviz:
    ```
    [ INFO] [1664278804.499219200]: rviz version 1.14.14
    [ INFO] [1664278804.499295300]: compiled against Qt version 5.12.8
    [ INFO] [1664278804.499311300]: compiled against OGRE version 1.9.0 (Ghadamon)
    [ INFO] [1664278804.507856300]: Forcing OpenGl version 0.
    [ INFO] [1664278804.676199500]: Stereo is NOT SUPPORTED
    [ INFO] [1664278804.676283300]: OpenGL device: llvmpipe (LLVM 12.0.0, 256 bits)
    [ INFO] [1664278804.676335800]: OpenGl version: 3.1 (GLSL 1.4).
    ```
* System locale, i.e. the output of `echo "$LANG $LC_NUMERIC"`: zh_CN.UTF-8

**Comment by rhaschke** [comment]
I cannot reproduce that problem. For me, views restore their position as expected.
Please try updating to the latest rviz release (1.14.19) and report back (providing your full .rviz config) if the problem persists.

**Comment by ysl-design** [comment]
Sorry, the steps described before are a little less, I will re-describe
1.I added 3 Camera plugins and 1 Image plugin to the rviz, then added 2 Views panels,
2.and then selected “Save” when closing rviz to save the added plugins.
3.Start rviz again, the Views panel is indeed there, and then delete the Views Panel through the "Delete Panel"
![image](https://user-images.githubusercontent.com/67178569/193215503-0ca38cc7-ec1d-4dd0-a3a6-c9ddba075b6d.png)
There are 3 Views here because one is added by rviz by default
4.Add two new Views Panels
5.Again, close rviz, choose “Save”
![image](https://user-images.githubusercontent.com/67178569/193216006-9b476380-ab5f-424a-9d5d-d743135bfbf9.png)
6.Start rviz again，the problem appears.
I updated the latest version of rviz and the problem still exists.
My config file is as follows
[1.zip](https://github.com/ros-visualization/rviz/files/9682298/1.zip)

**Comment by rhaschke** [comment]
I can confirm that all views panels are lost after deleting a single one.

**Comment by rhaschke** [comment]
Actually, the behavior is more intricate: If you add additional `Views` panels and then remove one of those non-default ones, the removed one will not show up after reloading anymore (as expected), but also the default one will not show up anymore.
In contrast, if you remove the default `Views` panel (the last one in all those lists), all other `Views` panels will show up correctly.
I don't have time to investigate this very artificial problem in more depth. Just don't add and remove additional `Views` panels. It doesn't make sense to have more than one anyway :wink: 

The difference in .rviz files is just within the `QMainWindowState`.
