### ISSUE TITLE
I want to get the key release event in rviz::Tool class

### ISSUE THREAD

**Issue by lidongxu111** [ros-visualization/rviz#1770]
I want to get the key release event in rviz::Tool class

but the function processKeyEvent can only get pressed key event.

Is there any way to get released key event?

**Comment by rhaschke** [comment]
Not yet. You would need to augment the class and build from source. Is there a special reason you need this event?

**Comment by lidongxu111** [comment]
I've rewritten the ProcessKeyEvent function, but it can only receive keyboard press events, not keyboard release events

**Comment by lidongxu111** [comment]
![image](https://user-images.githubusercontent.com/110215522/196122262-3ad55aaa-caad-4fac-95b3-1ed781c5de14.png)

**Comment by lidongxu111** [comment]
so，Why is this KeyRelease not responding

**Comment by rhaschke** [comment]
Because RenderPanel is only overriding `keyPressEvent()` not `keyReleaseEvent()`:
https://github.com/ros-visualization/rviz/blob/6a234b4404c5ee71051f0b338ab8d5d2d931c27b/src/rviz/render_panel.h#L145

Again my question: Why do you need the release event? What do you want to achieve eventually?

**Comment by lidongxu111** [comment]
If I want this condition to be responsive, what do I do：
else if (event->type() == QEvent::KeyRelease && event->key() == 16777248) {
shift_pressing_ = false;
}

**Comment by rhaschke** [comment]
Indeed, if you need to receive KeyRelease events, you need to modify rviz itself as suggested in https://github.com/ros-visualization/rviz/issues/1770#issuecomment-1282533322

**Comment by lidongxu111** [comment]
But how do I modify rviz？
Modify render_panel.h?Do I put a KeyReleaseEvent function in there？

**Comment by rhaschke** [comment]
Yes, both in render_panel.h and render_panel.cpp. You need to include rviz in your catkin workspace of course.

**Comment by lidongxu111** [comment]
I've changed  render_panel.h in a file on my own virtual machine，and I don't have this render_panel.cpp，But processKeyEvent doesn't work

**Comment by lidongxu111** [comment]
![1666165633886](https://user-images.githubusercontent.com/110215522/196629039-1b35adb3-2494-4db4-b6d4-e6defc881c58.jpg)

**Comment by rhaschke** [comment]
> I've changed render_panel.h in a file on my own virtual machine，and I don't have this render_panel.cpp

Obviously, you need to clone the rviz repo (this one) into your catkin workspace. Just changing render_panel.h in /opt/ros doesn't help at all.

**Comment by lidongxu111** [comment]
omg，Thank you very much for your help.
