### ISSUE TITLE
Problems with loading rviz configuration file from command line 

### ISSUE THREAD

**Issue by giomar207** [ros-visualization/rviz#1771]
Hi, 
I am a newcomer to rviz. I looked for an answer to my problem in the FAQ but I was not able to find a solution, therefore I am writing this message. I do not know if I found a bug or if I am doing something wrong. I report the information you need to understand the issue correctly.
If I run rviz without any configuration file defined by -d parameters, rviz works fine. However, If I execute the shell command with the path for the configuration file, rviz is able to visualize the images correctly, but it does not respond anymore, and if I want to change anything I have to use Ctrl-c for closing the application from the terminal. 
Any suggestions or any other link where I can solve my problem? 
Thank you in advance. 
Giovanni

Describe your issue here and explain how to reproduce it.

### Your environment
* OS Version: Ubutnu 20.04 on Windows 11, using WSL2
* ROS Distro: Noetic
* RViz, Qt, OGRE, OpenGl version as printed by rviz:
[ INFO] [1666172504.819629439]: rviz version 1.14.19
[ INFO] [1666172504.819672411]: compiled against Qt version 5.12.8
[ INFO] [1666172504.819692429]: compiled against OGRE version 1.9.0 (Ghadamon)
* If source build, which git commit?
* System locale, i.e. the output of `echo "$LANG $LC_NUMERIC"`: C.UTF-8
  Before reporting a rendering issue, try running RViz with `LANG=C rviz`!

**Comment by rhaschke** [comment]
From your description, it sounds like the display plugins loaded by your custom config file are broken or just too busy to allow for user interaction. Hence, you should check, which of those plugins causes the observed issue. If you identified one, check the rate of messages it needs to process.
