### ISSUE TITLE
Rviz - 2 Cameras Realsense - ROS Foxy

### ISSUE THREAD

**Issue by alvaropascuaI** [ros-visualization/rviz#1774]
I want to launch 2 realsense cameras at the same time and then rebuild it with rviz
I have followed the following [tutorial](https://github.com/IntelRealSense/realsense-ros/wiki/showcase-of-using-3-cameras-in-2-machines) but when choosing the fixed frame if I put for example camera 1, the topics of camera 2 fail me and they are not shown in the viewer
Also later when showing the points, how can I make them save and not get lost every time?

![image](https://user-images.githubusercontent.com/97975075/203783687-06999f93-5d57-4d48-a4d7-a3881f912bd7.png)

I launch cameras with this:

> ros2 launch realsense2_camera rs_launch.py initial_reset:=true enable_pointcloud:=true serial_no:=_153222070827 camera_name:=camera_right

> ros2 launch realsense2_camera rs_launch.py initial_reset:=true enable_pointcloud:=true serial_no:=_012322061981 camera_name:=camera_left

I launch rviz with this

> ros2 run rviz2 rviz2

* OS Version: e.g. Ubuntu 20.04
* ROS Distro: Foxy

**Comment by rhaschke** [comment]
Please file your issue over at https://github.com/ros2/rviz. This is the ROS1 repo.
