### ISSUE TITLE
Not save pointcloud map

### ISSUE THREAD

**Issue by alvaropascuaI** [ros-visualization/rviz#1776]
I launch topics that i need for see in rviz pointcloud, but dont save point cloud map, what i need configure ?

I launch camera with this `roslaunch realsense2_camera rs_camera.launch camera:=cam_2 serial_no:=153222070827 filters:=spatial,temporal,pointcloud`

I launch rviz with `rviz` on terminal

![image](https://user-images.githubusercontent.com/97975075/207001667-2bca212c-369b-4170-939c-35c3788bc14b.png)

### Your environment
* OS Version: Ubuntu 20.04
* ROS Distro: Noetic

**Comment by alvaropascuaI** [comment]
What I want is for a map to be generated with the points that the rviz shows me, as with RTABMAP, but the problem is that a map is not generated from those point clouds

**Comment by rhaschke** [comment]
I don't know about `RTABMAP`. In any case, rviz doesn't perform any processing, it just displays information available in your ROS system. So, if you need to process the point cloud into some map, this should be handled elsewhere.

**Comment by alvaropascuaI** [comment]
I understand, thank you so much i will search more information
