### ISSUE TITLE
rviz2 load dump

### ISSUE THREAD

**Issue by Horizonzhou** [ros-visualization/rviz#1800]
[ERROR] [1687762051.659290820] [rviz2]: ItemIdentityException: SceneNode not found. in SceneManager::_destroySceneNode at /home/zwx/.local/ros2_foxy/build/rviz_ogre_vendor/ogre-v1.12.1-prefix/src/ogre-v1.12.1/OgreMain/src/OgreSceneManager.cpp (line 770)
terminate called after throwing an instance of 'Ogre::ItemIdentityException'
  what():  ItemIdentityException: SceneNode not found. in SceneManager::_destroySceneNode at /home/zwx/.local/ros2_foxy/build/rviz_ogre_vendor/ogre-v1.12.1-prefix/src/ogre-v1.12.1/OgreMain/src/OgreSceneManager.cpp (line 770)
fish: “rviz2” terminated by signal SIGABRT (Abort)

![image](https://github.com/ros-visualization/rviz/assets/41419032/e1410db9-669d-424b-a062-a81ab2cf6e81)

**Comment by rhaschke** [comment]
Please file rviz2 issues over here: https://github.com/ros2/rviz
