### ISSUE TITLE
No tf data. Actual error: Fixed Frame [map] does not exist

### ISSUE THREAD

**Issue by 999gzd** [ros-visualization/rviz#1806]
Describe your issue here and explain how to reproduce it.

### Your environment
* OS Version: e.g. Ubuntu 18.04
* ROS Distro: [Kinetic | Melodic | Noetic]
* RViz, Qt, OGRE, OpenGl version as printed by rviz:
    ```
    paste your console output here
    ```
* If source build, which git commit?
* System locale, i.e. the output of `echo "$LANG $LC_NUMERIC"`:
  Before reporting a rendering issue, try running RViz with `LANG=C rviz`!

**Comment by rhaschke** [comment]
Obviously, you need to publish your tf data. Please provide detailed error output the next time.
