### ISSUE TITLE
Using with a python virtual environment to import ros packages. Making a pyinstaller executable.

### ISSUE THREAD

**Issue by programmeddeath1** [ros-visualization/rviz#1839]
Is it possible to load rviz and ros1 components and libraries from a python virtual environment?

I am trying to package my application as a PyQT app. I am building the executable using pyinstaller. When trying to build the pyinstaller executable, the system installed mpl_toolkits is causing conflicts with the user installed mpl_toolkits that is being used by another package called ultralytics. Hence the mpl_toolkits is getting imported from the wrong location and matplot lib fails when the executable is run with  - "cannot import name  'rcParams' ifrom matplotlib,axes(in _python_path_.)"

If i try to uninstall the python3-matplotlib, it thereby removes ros-noetic-desktop* ros-noetic-viz* and all ros packages too, so there seems to be a dependency with ros packages.

Do you know of any other method in which ros python apps can be packaged?

###  Environment
* OS Version: e.g. Ubuntu 20.04
* ROS Distro: [ Noetic ]
* RViz, Qt, OGRE, OpenGl version as printed by rviz:

```
[ INFO] [1723524586.244750331]: rviz version 1.14.20
[ INFO] [1723524586.244877444]: compiled against Qt version 5.12.8
[ INFO] [1723524586.244912826]: compiled against OGRE version 1.9.0 (Ghadamon)
[ INFO] [1723524586.307195975]: Forcing OpenGl version 0.
[ INFO] [1723524587.552751404]: Stereo is NOT SUPPORTED
[ INFO] [1723524587.552812617]: OpenGL device: Mesa Intel(R) HD Graphics 630 (KBL GT2)
[ INFO] [1723524587.552848592]: OpenGl version: 4.6 (GLSL 4.6) limited to GLSL 1.4 on Mesa system.
```

* System locale, i.e. the output of `echo "$LANG - en_US.UTF-8

**Comment by rhaschke** [comment]
This question is not rviz-related and should be better asked at https://answers.ros.org. Please, post real issues and bug reports here only.
To quickly answer your question: ROS packages rely on system-installed python packages.
