### ISSUE TITLE
image glitch when using Rpib+ RTP source

### ISSUE THREAD

**Issue by lida2003** [ros-visualization/rviz#1840]
Simply modify [video-viewer from jetson code](https://github.com/dusty-nv/jetson-utils) and publish image with local ROS time stamp.

And I got image glitch compared to jetson program. I'm NOT sure what caused issue, any help is well appreciated.

### Your environment
* OS Version: Ubuntu 20.04.6 LTS
* Hardware: Jetson Orin Nano 8GB
* ROS Distro: [Noetic]
* RViz
    ```
    $ cat /etc/os-release
    NAME="Ubuntu"
    VERSION="20.04.6 LTS (Focal Fossa)"
    ID=ubuntu
    ID_LIKE=debian
    PRETTY_NAME="Ubuntu 20.04.6 LTS"
    VERSION_ID="20.04"
    HOME_URL="https://www.ubuntu.com/"
    SUPPORT_URL="https://help.ubuntu.com/"
    BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
    PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
    VERSION_CODENAME=focal
    UBUNTU_CODENAME=focal
    ```

Here is my test video [sj1NJsEtm9Q](https://youtu.be/sj1NJsEtm9Q)
Here is my test code [uav_camera.cpp](https://github.com/SnapDragonfly/uav_mavlink/blob/main/src/uav_camera/uav_camera.cpp)

Jetson's code is OK. There are quite a lot of glitches in rviz.

Anyone knows why?

**Comment by rhaschke** [comment]
This question should be better asked at https://answers.ros.org. Please, post real issues and bug reports here only.
I don't think this is a real rviz issue, but I couldn't spot an obvious issue in your code either.
