### ISSUE TITLE
What are the resources for 3D reconstruction + robot visualization?

### ISSUE THREAD

**Issue by guotong1988** [ros-visualization/rviz#1841]
Thank you very much!!

**Comment by rhaschke** [comment]
Can you please clarify you question? What resources are you referring to?

**Comment by guotong1988** [comment]
Thank you for the response.

I am mainly looking for ways to align and visualize a 3D reconstructed model (prediction results) using tools like RViz for visualization.

**Comment by rhaschke** [comment]
rviz is a visualization tool. It doesn't provide compute methods like alignment. There are numerous [display plugins](https://wiki.ros.org/rviz/DisplayTypes), including [markers](https://wiki.ros.org/rviz/DisplayTypes/Marker) (e.g. for meshes) and [point clouds](https://wiki.ros.org/rviz/DisplayTypes/PointCloud). And, of course, you can write your own plugin.
