### ISSUE TITLE
StampedTwist display for rviz  (ros-pkg ticket #3811)

### ISSUE THREAD

**Issue by hershwg** [ros-visualization/rviz#294]
I'd like to visualize twists in rviz for debugging some teleoperation stuff.  In particular, I am converting a twist between frames, and I'm not certain that I've done the conversion correctly.  To check it, I plan to display the twist and visually confirm correctness.

trac data:
- Owner: **hersh**
- Reporter: **sglaser**
- Reported at: **Wed Feb 10 13:11:14 2010**
- URL: http://code.ros.org/trac/ros-pkg/ticket/3811

**Comment by oscar-lima** [comment]
This issue is addressed and solved by:

http://jsk-docs.readthedocs.io/en/latest/jsk_visualization/doc/jsk_rviz_plugins/plugins/twist_stamped.html

jsk_rviz_plugins

you can get binaries from:

sudo apt install ros-kinetic-jsk-rviz-plugins

I propose this issue to be closed.

**Comment by wjwwood** [comment]
Thanks @oscar-lima. Since there is a package out there that implements this, I'll close this.

If anyone wants to convince the JSK team to split that out into a separate package or to try and integrate it into rviz itself, they're welcome to do that.

Feel free to continue discussing here, and I can reopen this issue if necessary.

**Comment by paszoujp** [comment]
> This issue is addressed and solved by:
> 
> http://jsk-docs.readthedocs.io/en/latest/jsk_visualization/doc/jsk_rviz_plugins/plugins/twist_stamped.html
> 
> jsk_rviz_plugins
> 
> you can get binaries from:
> 
> sudo apt install ros-kinetic-jsk-rviz-plugins
> 
> I propose this issue to be closed.

The link has expired

**Comment by oscar-lima** [comment]
Here is the updated link:

https://jsk-visualization.readthedocs.io/en/latest/jsk_rviz_plugins/plugins/twist_stamped.html
