### ISSUE TITLE
rviz should provide tools to display covariance data  (ros-pkg ticket #4857)

### ISSUE THREAD

**Issue by hershwg** [ros-visualization/rviz#381]
See discussion here:

 http://answers.ros.org/question/263/how-can-i-visualize-covariance-data-using-ros

trac data:
- Owner: **hersh**
- Reporter: **joq**
- Reported at: **Mon Mar  7 07:48:23 2011**
- URL: http://code.ros.org/trac/ros-pkg/ticket/4857

**Comment by NikolausDemmel** [comment]
> I never found the time to dedicate to merging this into rviz. You can find what I did in the hydro branch of rviz_plugin_covariance, though: https://github.com/laas/rviz_plugin_covariance/tree/hydro

I just had a look at this, and it seems to work ok on indigo. However, in my case I have 2D covariances (only x, y and yaw), and the display seems to flip between being a flat circle in the x-y plane (as expected) and a flat circle in the y-z plane instead, which is wrong.

This is the output I get from the plugin in the y-z plane case. 

```
[ INFO] [1444726412.089431527]: Position:
Vector3(1.19936, 0.346209, 0)
Positional part 3x3 eigen values:
0
46.188
140.508
Positional part 3x3 eigen vectors:
         0 -0.0482425   0.998836
         0   0.998836  0.0482425
         1          0          0
Sphere orientation:
Quaternion(0.706901, -0.0170613, -0.000411789, 0.0170613)
Radian(0.0241447) Radian(-0.0241587) Radian(-0.00116504)
Sphere scaling:
Vector3(0, 6.79617, 11.8536)
Rotational part 3x3 eigen values:
0
0
2.32922e+06
Rotational part 3x3 eigen vectors:
1 0 0
0 1 0
0 0 1
Cone orientation:
Quaternion(1, 0, 0, 0)
Radian(0) Radian(0) Radian(0)
Cone scaling:
Vector3(0, 0, 1526.18)
[ WARN] [1444726412.089495965]: computeRotation found non-unitary quaternion!
```

The warning stems from [this line in the code](https://github.com/laas/rviz_plugin_covariance/blob/2cfe70e9f4dd8eef3ae168c7713055e75fa62cee/src/covariance_visual.cpp#L55), which suggests that in those cases the rotation matrix is somehow invalid, resulting in a not-normalized quaternion after conversion.

Can anyone tell what is going wrong here?

**Comment by Ellon** [comment]
Hello!

I recently found the code from rviz_plugin_covariance and developed a some more things on top of it. How is thie status of this issue? If it's not addressed I may be able to add as a pull request to rviz.

@NikolausDemmel I had similar warnings here, this is basically a debug debug which was coded as info, showing the result of the covariance visual computation. I'm going to do some more tests to verify if this part of the code is correct. I was only testing it with 3D covariances up to now, but I'll check with 2D ones as well.

**Comment by NikolausDemmel** [comment]
@wjwwood, I think we can close this with #1096 being merged?

**Comment by wjwwood** [comment]
Yes, thank you.
