### ISSUE TITLE
changing an interactive marker interrupts dragging  (ros-pkg ticket #5327)

### ISSUE THREAD

**Issue by hershwg** [ros-visualization/rviz#475]
I would like to change the color of an interactive marker while dragging it around the screen.  I re-insert a marker with the same name and it gets swapped out very quickly.  However, in order to continue dragging at that point I need to release the mouse button and click again on the control I was using, making it pretty unusable.  Ideally on re-insertion the new marker would preserve enough state to allow me to continue to drag the marker.

trac data:
- Owner: **hersh**
- Reporter: **gjones**
- Reported at: **Thu Jan  5 14:58:59 2012**
- URL: http://code.ros.org/trac/ros-pkg/ticket/5327

**Comment by carlosjoserg** [comment]
Hi @hershwg 

This is very old, but I'm in the same situation now, and [this](http://answers.ros.org/question/206438/in-rviz-how-to-change-the-color-of-interactive-marker-at-runtime/) and [this](http://answers.ros.org/question/171706/rviz-interactive-markers-color-change-runtime/) questions are not that old and remain unanswered. So...

How do you actually do that? I was trying the Update message inside the callback function of the Feedback message. At most, I could change the color, but I had to insert the marker again, so I loose the pose. And I tried copying the pose from the Feedback to the Update but it is somehow scaled.

Thanks
