### ISSUE TITLE
rviz: crash when mousing over or dragging an interactive marker when it is deleted  (ros-pkg ticket #5377)

### ISSUE THREAD

**Issue by hershwg** [ros-visualization/rviz#496]
If you are mousing over an interactive marker control or dragging one at the time when the interactive marker server sends an update which deletes it, rviz will crash.

It should not.

trac data:
- Owner: **hersh**
- Reporter: **hersh**
- Reported at: **Wed Feb 22 17:12:43 2012**
- URL: http://code.ros.org/trac/ros-pkg/ticket/5377

**Comment by Saki-Chen** [comment]
I got this error again in melodic

**Comment by rhaschke** [comment]
@Saki-Chen, please open a new issue and exactly report how to reproduce this issue. How can you drag a deleted marker?
