### ISSUE TITLE
Undefined reference to vtable for Assimp::IOSystem' 

### ISSUE THREAD

**Issue by gpraust** [ros-visualization/rviz#561]
When compiling rviz from groovy source on ubuntu 12.04 on pandaboard (armhf) I am getting the following error. 

Building CXX object src/image_view/CMakeFiles/rviz_image_view.dir/image_view.cpp.o 
/home/user/ros_catkin_ws/devel_isolated/rviz/lib/librviz.so: undefined reference to vtable for Assimp::IOSystem' /home/user/ros_catkin_ws/devel_isolated/rviz/lib/librviz.so: undefined reference to typeinfo for Assimp::IOSystem' collect2: ld returned 1 exit status make[2]: * 

After a quick Google search I discovered this page (http://gcc.gnu.org/faq.html#vtables) which suggests to overcome this that "all virtual methods that are not pure are defined. Note that a destructor must be defined even if it is declared pure-virtual"

Have all methods been defined correctly? or am I missing something?

**Comment by wjwwood** [comment]
Closing since it is likely an upstream bug.
