### ISSUE TITLE
Width of Path in RViz can not be changed?

### ISSUE THREAD

**Issue by cnpcshangbo** [ros-visualization/rviz#650]
I am going to report my project with a record of RViz, however, Width of Path can not be changed. If I can get the Path to be thicker, the audience may see the lines more clearly.

**Comment by tlind** [comment]
I implemented this in pull request #842. This required the addition of a new display style "Billboards" for paths, similar to how it is done in the Grid display, since the width cannot be changed for the default "Lines" style.

**Comment by wjwwood** [comment]
I've merged @tlind's pr #842, so I'm going to close this for now.
