### ISSUE TITLE
Severe memory leak when displaying MarkerArrays with current hydro rviz from .debs

### ISSUE THREAD

**Issue by skohlbr** [ros-visualization/rviz#695]
I get severe leaking when displaying a MarkerArray using the hydro version of rviz installed from .debs (12.04, AMD64). Displaying a MarkerArray for a octomap, memory gets filled up at a rate of about 2 GB in 10 seconds. See attached images below. I transmitted a MarkerArray based octomap visualization and paused playing my bagfile. Time does not advance and no new MarkerArray data gets published. With the hydro version of rviz, the following happens: 
![mem_fill_rviz_hydro_4gb](https://f.cloud.github.com/assets/205963/1418197/4976260c-3fad-11e3-89c8-625b1fde835b.png)
![mem_fill_rviz_hydro_8gb](https://f.cloud.github.com/assets/205963/1418198/522034c8-3fad-11e3-98aa-4bbe8f0f79b2.png)
The interesting parts are the memory consumption in "top" (left) and the ROS wall time in rviz (right).

The rviz version available from .debs in groovy does not exhibit this behavior and performs as expected.

**Comment by radhaanu26** [comment]
I am trying to visualise similar tool like rviz for visualising bag files og 10-20 GB size. And as expected it is creating memory leakage and it is either freezing or giving segmentation fault. Any idea how did rviz community solved this issue?
