### ISSUE TITLE
Image display replicates first raster of display as the last raster as well

### ISSUE THREAD

**Issue by joydeep-b** [ros-visualization/rviz#697]
When visualizing messages from a topic of type `sensor_msgs::Image` and encoding `RGB8`, the last raster at the bottom of the display is replicated from the top raster. Note that this replication is done at the screen resolution, not the resolution of the message. In the attached image, the first pixel in the published message has a red pixel, and the individual pixels of the message are clearly discernible since it is not at the same resolution as the display. However, at the bottom of the image display, the last raster drawn is clearly a duplicate of the first raster, at the display resolution (not the resolution of the image message).

**Edit:** output when starting up `rviz`:

```
[ INFO] [1383780177.667530003]: rviz revision number 1.8.17
[ INFO] [1383780177.667667808]: compiled against OGRE version 1.7.3 (Cthugha)
[ INFO] [1383780178.292964941]: Loading general config from [/home/joydeepb/.rviz/config]
[ INFO] [1383780180.019522099]: Texture for pass 0: creating with size 1 x 1
[ INFO] [1383780180.024091608]: Texture for pass 1: creating with size 1 x 1
```

- ros version: Fuerte
- `uname -a`:
 - `3.2.0-24-generic #39-Ubuntu SMP Mon May 21 16:52:17 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux`
- `cat /etc/lsb-release`:

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=12.04
DISTRIB_CODENAME=precise
DISTRIB_DESCRIPTION="Ubuntu 12.04.2 LTS"
```

![image](https://f.cloud.github.com/assets/3406269/1487749/ffb45f7c-4739-11e3-88af-958e54faf818.png)

**Comment by wjwwood** [comment]
I'm going to close this since it appears to be fixed in hydro+ and we will not be releasing new versions for fuerte. If someone who is interested in supporting fuerte would like to work on this please comment here.
