### ISSUE TITLE
Rviz from binaries has low fps when displaying PointCloud2

### ISSUE THREAD

**Issue by mintar** [ros-visualization/rviz#775]
On my high-end laptop, the FPS drops from ~28 to ~7 when displaying a Kinect PointCloud2 at 15Hz. Interestingly, this only occurs with the version from the binary debs (1.10.16), not when building the **same version** from source.

Steps to reproduce:
- source /opt/ros/hydro/setup.bash
- start Rviz and display Kinect PointCloud2
- bug appears: 6 fps

In an attempt to find the offending commit, I built rviz from source, but then the bug disappears:
- clone tag **1.10.6** from git into an empty catkin workspace
- catkin_make -DCMAKE_BUILD_TYPE=Release
- bug is gone: 28 fps

I could narrow it down to either `librviz.so` or `libdefault_plugin.so`:
- rviz executable from `/opt` + .so's from `/opt`: bug.
- rviz executable from `/opt` + .so's from `/home`: no bug.
- rviz executable from `/home` + .so's from `/home`: no bug.

Are the binary libraries perhaps built with funny compile options?

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros2-logging-using-fmt/25978/10
