### ISSUE TITLE
Create a conversion tool from vcg to rviz configuration

### ISSUE THREAD

**Issue by vvanirudh** [ros-visualization/rviz#780]
I know that this issue has been raised before, but it was not resolved then. It was just closed as Groovy was not yet released. But I have just converted from Fuerte to Indigo and all the rviz configuration files that my project are in vcg format and it is going to take a lot of time to convert them. It would be nice to have a script which can do it.

**Comment by dbolkensteyn** [comment]
@wjwwood this issue can probably be closed - the more time passes, the less relevant this becomes
