### ISSUE TITLE
Unable to run rviz on headless machine (OpenGL failure)

### ISSUE THREAD

**Issue by edgimar** [ros-visualization/rviz#787]
When trying to run rviz via an x2go connection, the following errors occur:

libGL: OpenDriver: trying /usr/lib/x86_64-linux-gnu/dri/tls/swrast_dri.so
libGL: OpenDriver: trying /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
libGL error: failed to load driver: swrast

The file /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so does exist on my system (64-bit Ubuntu 13.04, with ros-hydro installed on it).

Mind you that I *am* able to run glxgears just fine via the x2go connection I have, despite the fact that running it also produces the following error: "libGL error: failed to load driver: swrast".

Others have reported similar errors when attempting to run rviz remotely over an X11 connection.  (see http://answers.ros.org/question/125861/running-rviz-through-x-forwarding-on-headless-machine/ ).

**Comment by wjwwood** [comment]
Ok, well I'm going to close this for now, please comment here if anyone else has a more concrete solution that would allow rviz to run on a headless machine.

**Comment by zdx3578** [comment]
A common task is to SSH into the robot's computer and run RVIZ to get the laser output and other visualization. Running RVIZ directly on the remote computer will not work due to the way RVIZ is implemented. The workaround is to run RVIZ locally. To do this we need to set the local computer to locate the remote MASTER NODE in order to display the right information.

**Comment by renschler** [comment]
@ZdenekM it would be awesome if you could provide some more details on your turboVNC solution

I am trying to run the google cartographer SLAM demo (https://google-cartographer-ros.readthedocs.io/en/latest/) which uses rviz. I am using ubuntu 14.04, ROS kinetic, on an AWS machine, with an X11 connection.

I see logs being printed to the command line which suggest the SLAM demo is running, but the visualization is a static image of rviz which says "initializing". 
<img width="446" alt="screen shot 2017-06-29 at 1 31 37 pm" src="https://user-images.githubusercontent.com/3973468/27704912-c4ca744e-5cd1-11e7-8f88-8299c87f0134.png">

I saw the following errors:
```
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
```

**Comment by sebaleme** [comment]
Hi, 
I can only confirm that I noticed the same behaviour. I cannot start RVIZ when accessing my remote linux desktop with X2GO. But glxgears works just fine, with an acceptable frame rate.

```
(base) lsm1so@ABTZ0IY7:~$ LIBGL_DEBUG=VERBOSE rviz
[ INFO] [1615286558.681773788]: rviz version 1.12.4
[ INFO] [1615286558.681828323]: compiled against Qt version 5.9.5
[ INFO] [1615286558.681838582]: compiled against OGRE version 1.9.0 (Ghadamon)
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/lsm1so/.drirc: No such file or directory.
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/lsm1so/.drirc: No such file or directory.
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/lsm1so/.drirc: No such file or directory.
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/lsm1so/.drirc: No such file or directory.
Segmentation fault (core dumped)
```

However, in order to get X2GO working, I had to install the mesa OPENGL, which replaces the NVIDIA opengl. I suppose this library is the issue with rviz. What does work is using X2GO to access my linux machine, and then from this linux machine, I use docker with the NVIDIA opengl. Through ULTRAVNC, I can access my docker environment, and start rviz from there.
I also tried to start rviz via a X11 windows on my client through SSH, but I get the same error, seg fault. With GDB, I can see that it happens somewhere in the OGRE-1.9.0/RenderSystem_GL.so.1.9.0 library, but I don t have the symbols for that lib so I cannot go further.

**Comment by nov05** [comment]
> Hi, I can only confirm that I noticed the same behaviour. I cannot start RVIZ when accessing my remote linux desktop with X2GO. But glxgears works just fine, with an acceptable frame rate. Note that my colleagues who have a working rviz (with another remote solution) are also having the errors "no such file or directory".
> 
> ```
> (base) lsm1so@ABTZ0IY7:~$ LIBGL_DEBUG=VERBOSE rviz
> [ INFO] [1615286558.681773788]: rviz version 1.12.4
> [ INFO] [1615286558.681828323]: compiled against Qt version 5.9.5
> [ INFO] [1615286558.681838582]: compiled against OGRE version 1.9.0 (Ghadamon)
> libGL: Can't open configuration file /etc/drirc: No such file or directory.
> libGL: Can't open configuration file /home/lsm1so/.drirc: No such file or directory.
> libGL: Can't open configuration file /etc/drirc: No such file or directory.
> libGL: Can't open configuration file /home/lsm1so/.drirc: No such file or directory.
> libGL: Can't open configuration file /etc/drirc: No such file or directory.
> libGL: Can't open configuration file /home/lsm1so/.drirc: No such file or directory.
> libGL: Can't open configuration file /etc/drirc: No such file or directory.
> libGL: Can't open configuration file /home/lsm1so/.drirc: No such file or directory.
> Segmentation fault (core dumped)
> ```
> 
> However, in order to get X2GO working, I had to install the mesa OPENGL, which replaces the nvidia OPENGL. I suppose this library is the issue with rviz. What does work is using X2GO to access my linux machine, and then from this linux machine, I use docker with the NVIDIA opengl. Through ULTRAVNC, I can access my docker environment, and start rviz from there. I also tried to start rviz via a X11 windows on my client through SSH, but I get the same error, seg fault. With GDB, I can see that it happens somewhere in the OGRE-1.9.0/RenderSystem_GL.so.1.9.0 library, but I don t have the symbols for that lib so I cannot go further.
> 
> Since some packages are working but not others, it is hard to tell if the bug is coming from rviz (not respecting the opengl interfaces), mesa opengl (incompatibilities with nvidia) or X2GO.

I am using ROS, Gazebo, and Rviz under Ubuntu 16.04 on a Google Cloud Platform CPU VM instance, connecting with X2GO/X11. I have a very similar issue. 

<img src="https://raw.githubusercontent.com/nov05/pictures/refs/heads/master/Udacity/20250213_nd209_udacity_robotics_nanodegree/2025-02-24%2015_53_56-X2GO-robond-50-1740431631_stS1XSHADrobondXSHADPP0_dp32%40instance-20250224-015140.jpg" width=600>

**Comment by rhaschke** [comment]
@nov05: this is a well known error, unrelated to rviz. See https://robotics.stackexchange.com/questions/88896/time-is-out-of-dual-32-bit-range.
