### ISSUE TITLE
Memory leak/Large Buffer when TF is published

### ISSUE THREAD

**Issue by fbacim** [ros-visualization/rviz#802]
I'm currently running into issues with rviz and a pretty consistent memory usage growth issue, and I'm trying to figure out if this is a bug or it is intended to work this way. 

What I do is this: 
- start roscore
- start rviz using rosrun rviz rviz, without any display plugins other than grid

That works fine, and rviz sits at around 35.2MB. If I start gazebo/drcsim (and therefore start publishing to TF), rviz increases memory consumption at a rate of 1.7MB/s. That is until it reaches around 1.1~1.2GB, when it stops and stabilizes. I'm not sure if this is really a TF-related problem, but I'm guessing it is since it's the only thing rviz and gazebo have in common without any display plugins loaded. So, maybe it's some sort of buffer? Anyway, the title may not be correct, so feel free to change it.

**Comment by pbeeson** [comment]
Why was this ros::Duration(10*60) never made a parameter for Rviz?  We have an application that has hundred of TF frames, and Rviz essentially "Stabilizes" at 6GB of memory.  Why 10 minutes?  That's completely arbitrary and usually unnecessary.  We'd love to be able to set a param to make this 10 seconds.

**Comment by wjwwood** [comment]
@pbeeson probably nobody had time to implement it. I'd be happy to take a pr that adds a command-line option or an option in the GUI. I think we leave the 10 minutes as a default to preserve existing behavior. I'd be open to changing the default in a future ROS release though.

**Comment by wjwwood** [comment]
Since the leak was fixed in #807, I'm going to close this. @pbeeson if you'd like to track the fact that the steady state can consume too much memory, please open a new issue.
