### ISSUE TITLE
rviz does not save which tf frames were selected for viewing

### ISSUE THREAD

**Issue by jmtatsch** [ros-visualization/rviz#834]
also, when resetting the clock it forgets the current selection as well.

**Comment by wjwwood** [comment]
@jmtatsch can you give more details, like a step by step example on how to reproduce the problem, what exactly you mean by selected (boxes checked versus the selection tool), and pictures or a short video would be helpful in demonstrating the issue.

Also, what OS and ROS version are you using?

What is the exact version of rviz that you are using?

Without more information, I would not expect anyone could help you with this issue.

**Comment by jmtatsch** [comment]
OS: OS X 10.10.1
ROS indigo
rviz version 1.11.3 compiled against OGRE version 1.9.0
![screen](https://cloud.githubusercontent.com/assets/3080674/5658758/d5de49f0-9707-11e4-9790-611f31bb48b6.png)

**Comment by wjwwood** [comment]
Thanks for the updated information, I'll keep it here on the list and we'll get to it when we can.

**Comment by ipa-lth** [comment]
I just recognized the same issue.
The relevant information (which frame is checked) is stored in the .rviz file, however. It seems like the tf plugin is just not parsing (or using) anything after "All enabled".

If you want to reproduce the problem:
1. Uncheck some frames in the tf plugin
2. Save you configuration
3. Load the previous saved configuration again. (All frames will be checked again.) 

System:
Ubuntu 14.04
ROS Indigo
RViz version 1.11.7 (indigo). Compiled against OGRE version 1.8.1 (Byatis).

**Comment by zweistein** [comment]
Same issue on: Ubuntu 14.04; ROS Indigo, Rviz 1.11.8 and OGRE 1.8.1

**Comment by wjwwood** [comment]
Closing with https://github.com/ros-visualization/rviz/pull/946, please comment if this is still and issue.
