### ISSUE TITLE
rviz sometimes crashes on startup because of assertion in "rviz::ToolManager::toKey()"

### ISSUE THREAD

**Issue by hersh** [ros-visualization/rviz#851]
About 50% of the time I start rviz now, I'm seeing this crash before the window even comes up:
```
rviz: .../tool_manager.cpp:134: uint rviz::ToolManager::toKey(const QString&): Assertion `seq[0] > 65' failed.
```
I'm building this from the latest source.

The assertion was originally introduced here: https://github.com/ros-visualization/rviz/commit/8277331f6ac0743dcde4bc8284b9e3985e74e774 but has sinced moved to tool_manager.cpp.

The assertions should be replaced with conditionals, and the function signature should be changed to return a boolean success/error indicator and the output value should be returned by a reference parameter, like so:
```
bool toKey(QString const& str, uint& key_out);
```

**Comment by hdeeken** [comment]
@hersh: unfortunately i wasn't able to reproduce this, but i followed your suggestions and modified toKey accordingly. further i made sure that toKeys is only called if a shortkey is assigned to a tool. hope this fixes this issue ;)
