### ISSUE TITLE
Alpha transparency of mesh markers is broken

### ISSUE THREAD

**Issue by hersh** [ros-visualization/rviz#854]
Back in the old days when I worked on rviz, I made mesh markers obey the "alpha" field of their color, like all the other marker types do.  I made a test program that shows a bunch of combinations.  Recently (on HEAD) I was trying to show a semi-transparent mesh marker and it was shown opaque.  I re-ran my test program (src/test/mesh_marker_test.cpp) and I see that it no longer behaves as I intended.

Here is the new image:
![rviz-alpha-bug](https://cloud.githubusercontent.com/assets/1562730/6384040/0ae81d36-bd0c-11e4-8486-72d40c2b3534.png)

You can see the spheres in the image show the alphas as intended.

Here is an old correct image, from 9c5bbf9d6d41309aecd575f7310c26f471b8dff0 :
![rviz-no-bug](https://cloud.githubusercontent.com/assets/1562730/6384186/f4309d50-bd0d-11e4-837c-37ae1ae26ac5.png)

This version still worked: 4be608f13d65ec0ebb7ee46240e3274ff28627a0
This version has the bug: f75ad94

**Comment by trainman419** [comment]
It looks like this was introduced in #752 

It looks like your old program and @brindza 's changes are both achieving the same results, through different APIs.

Thoughts @brindza ?

**Comment by hersh** [comment]
Damn, it looks like I "+1"ed the original change.  I guess I didn't run my test program at the time. :(

**Comment by hersh** [comment]
Perhaps the issue is that the colorized meshes in #752 and the pr2-base meshes I show here use different features of the collada file type.  The test program mesh_marker_test.cpp should really include something like the rgb axes shown in #752 which showed the problem there.

**Comment by NikolausDemmel** [comment]
Just browsing through the issue list. I guess this can be closed, given #893 is released?

**Comment by NikolausDemmel** [comment]
(Maybe the port forward to jade is still missing, at least there is a label #893 that says so)

**Comment by wjwwood** [comment]
@NikolausDemmel I must have accidentally put that tag on there. Jade and Indigo are released from the same branch.

**Comment by wjwwood** [comment]
I'll let @hersh decide if this can be closed based on #893

**Comment by LemonPi** [comment]
This is still an issue

**Comment by rhaschke** [comment]
The default use case (`mesh_use_embedded_materials = False`) works as expected:
![image](https://user-images.githubusercontent.com/5376030/181629306-378e8808-679e-4076-b286-810494198030.png)

@LemonPi, if `mesh_use_embedded_materials = True` doesn't work as expected, please open a new issue and provide a corresponding mesh file comprising embedded materials.
