### ISSUE TITLE
Angular torque marker is dettached with negative z-axis torque

### ISSUE THREAD

**Issue by 130s** [ros-visualization/rviz#879]
Originally reported in https://github.com/tork-a/dynpick_driver/issues/16.

![img1](https://cloud.githubusercontent.com/assets/1840401/7228579/82ad9108-e795-11e4-987b-47b8071a188a.png)
![img2](https://cloud.githubusercontent.com/assets/238460/7197945/2d5cb262-e522-11e4-979d-6b2c64d28ef5.png)

To reproduce,
```
term-1$ rosrun rviz rviz   (then choose `base` as the fixed frame, and open Wrench plugin on RViz, choose "`/force`" topic)

term-2$ rosrun tf static_transform_publisher 0.0.0 0.0 0.0 0.0 0.0 2.0 /base /sensor 100

term-3$ rostopic pub -r 10 /force geometry_msgs/WrenchStamped '{ header: { seq: 1, stamp: 11, frame_id: "base" }, wrench: { force: { x: 0.5, y: 0.5, z: 1.0 }, torque: { x: 0.5, y: 0.5, z: -1.1 } } }'
```

```
$ dpkg -p ros-indigo-rviz|grep Vers
Version: 1.11.7-0trusty-20150328-2254-+0000
```
But another user reported that this happens on Hydro too.

**Comment by goretkin** [comment]
`stamp: now` works better than `stamp: 11` for reproducing the issue. am submitting a PR soon

**Comment by wjwwood** [comment]
@130s can you test https://github.com/ros-visualization/rviz/pull/883 to see if it solves your issue?

**Comment by 130s** [comment]
Will do this weekend.

**Comment by wjwwood** [comment]
Closing in favor of https://github.com/ros-visualization/rviz/pull/883
