### ISSUE TITLE
Crash on Effort plugin

### ISSUE THREAD

**Issue by ahoarau** [ros-visualization/rviz#892]
I noticed a crash in the Effort plugin (indigo) : 

```
[ WARN] [1432914059.915302803]: Message from [/lwr_sim/joint_state_publisher] has a non-fully-qualified frame_id [world]. Resolved locally to [world].  This is will likely not work in multi-robot systems.  This message will only print once.

Program received signal SIGSEGV, Segmentation fault.
0x00007fff9829ccc7 in rviz::EffortVisual::EffortVisual(Ogre::SceneManager*, Ogre::SceneNode*, boost::shared_ptr<urdf::Model>) ()
   from /opt/ros/indigo/lib/libdefault_plugin.so
```

It's when I select a valid joint state topic with a wrong _Robot Description_ value : 
- Joint States topic is `/lwr/joint_states`
- Robot description is at `/lwr/robot_description` (**not** at `/robot_description`)

This order cause the crash. Seems like `boost::shared_ptr<urdf::Model>` is null.

If I first input the correct Robot Description (`/lwr/robot_description`), then I select the joint state topic, it's working fine.

**Comment by wjwwood** [comment]
The naive thing to do would be to check the state of the model before trying to use it here:

https://github.com/ros-visualization/rviz/blob/indigo-devel/src/rviz/default_plugin/effort_visual.cpp#L34

But the real issue maybe that the `urdf_model` should never be null.
