### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by huang0171** [ros-visualization/rviz#910]
I want to install rviz
But I use gazebo 6
If I install rviz, systeme will install ogre-1.8-doc and remove libgazebo6-dev libogre-1.9-dev...
the gazebo_ros can't fonction without libgazebo6-dev!
What should I do? Do you have the same pb?
thx

**Comment by wjwwood** [comment]
The rviz binary in Trusty depends on Ogre-1.8. So you can build it from source (it will compile and work against Ogre-1.9) or you can upgrade to a version of ubuntu where rviz depends on Ogre-1.9 (like Vivid). This kind of incompatibility is why we set supported versions for particular ROS distributions, and for Jade the Gazebo version is 5.

In the future, please ask questions like this on answers.ros.org, and only escalate to github issues when you think there is a bug in rviz itself, also see: http://wiki.ros.org/Support

Thanks!
