### ISSUE TITLE
Unselecting a tabbed panel disables its display.

### ISSUE THREAD

**Issue by hersh** [ros-visualization/rviz#940]
This bug was caused by pull request #914.

You can have multiple panels on top of each other in a tabbed configuration, as shown here with "Camera" and "Displays" tabbed:

![tabbed_panels1](https://cloud.githubusercontent.com/assets/1562730/10920220/e48742e2-8223-11e5-9cfb-a00612b362b3.png)

Before the merge of #914, you could enable a camera display (or anything else with an associated panel) and dock it in one of those tabbed views, and the display would stay enabled even when its tab was not selected (and thus invisible).

The new behavior is that you can enable a camera display, dock its panel into a tabbed area, select a different tab, and your camera display disables and its tab disappears.

I personally use tabbed panels all the time, and this change makes them pretty much unusable.

I wasn't able to duplicate the bug that #914 was supposed to fix in the previous version of rviz, so I'm not sure how to change it so that his bug was fixed and mine is too.

**Comment by EricCousineau-TRI** [comment]
I believe I've also been bitten by this behavior. I've filed a specific instance of it in #1368, with a screenshot workflow thing.
