### ISSUE TITLE
Undefined reference YAML::Emitter::Write

### ISSUE THREAD

**Issue by SquirrelCZE** [ros-visualization/rviz#954]
Hi folks, I'have been trying to compile ros-jade-desktop and this package... but run into a problem during compilation

```
[ 56%] Linking CXX executable ../../devel/lib/rviz/rviz
../../devel/lib/librviz.so: undefined reference to `YAML::Emitter::Write(std::string const&)'
```

any ideas what I can done to get rid of this? I try to compile it on archlinux system with actual yaml-cpp library and actual ros-jade-rviz... 

thanks

P.S: if you would need any more info, I am more than willing to give it :)

**Comment by wjwwood** [comment]
What version of `yaml-cpp` are you using?

**Comment by SquirrelCZE** [comment]
yaml-cpp 0.5.2-5

**Comment by wjwwood** [comment]
The fact that it is a linker error is interesting. It implies that the header that it compiled against no longer matches the shared library it is linking against. Did you update the version of `yaml-cpp` between the first build of `rviz` and a subsequent build? Without being able to reproduce the issue I'm just guessing.

**Comment by SquirrelCZE** [comment]
I just reinstalled it...

Iv've got problems with another packaged and now even "catkin_make" doesn't work and got errors ... all linking errors it seems

I wil post question in anwsers.ros.org :/

**Comment by SquirrelCZE** [comment]
Well, it seems like removing all ros-jade packages and relative packages from system and reinstall it all worked to repair the problem. I can close this here then I suppose
