### ISSUE TITLE
How to control the interactive markers positions in RVIZ?

### ISSUE THREAD

**Issue by AmirSassi** [ros-visualization/rviz#956]
Hi,

Actually, i created an interactive marker in RVIZ and i want to control its position. I mean when the interactive marker reaches a specified position it should be blocked in that position and will not have the right to move forward. Hence you will have just the right to move it back, right or left.

Do you have any suggestions for that?
Thanks.

**Comment by wjwwood** [comment]
Sounds like collision behavior? Either way that would just be implemented in the interactive marker server. See: http://wiki.ros.org/rviz/Tutorials/Interactive%20Markers%3A%20Getting%20Started
