### ISSUE TITLE
QUESTION: Migrating to Qt5

### ISSUE THREAD

**Issue by OAkyildiz** [ros-visualization/rviz#967]
Hello,

As the title says, do you plan to migrate to Qt5?

**Comment by wjwwood** [comment]
We've been discussing a move to Qt5 for all of ROS for the next LTS ROS Kinetic (due out this May). There will likely be more movement on this in about three weeks when we're supposed to make a decision about whether or not to go for it. If we did, we'd update the Kinetic REP3 pr: https://github.com/ros-infrastructure/rep/pull/106

There is a pr for Qt5 (conditional) support for rviz already, but I've not had time to try it out: https://github.com/ros-visualization/rviz/pull/909

**Comment by wjwwood** [comment]
I'm gonna close this for now since we already have two places where we can discuss this. You can continue to comment here if you wish though.

**Comment by OAkyildiz** [comment]
Thanks for the info!
